package com.voidsrift.riftflux.avatar.glider;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGlider2 extends ModelBase {
    ModelBiped player = new ModelBiped();
    ModelRenderer Shaft;
    ModelRenderer NoduleTop;
    ModelRenderer NoduleBottom;
    ModelRenderer TopLeftBar;
    ModelRenderer LeftBar1;
    ModelRenderer RightBar1;
    ModelRenderer LeftBar2;
    ModelRenderer RightBar2;
    ModelRenderer LeftBottomBar1;
    ModelRenderer RightBottomBar2;
    ModelRenderer LeftTopFan1;
    ModelRenderer RightTopFan1;
    ModelRenderer TopRightBar;
    ModelRenderer LeftTopFan2;
    ModelRenderer RightTopFan2;
    ModelRenderer LeftTopFan3;
    ModelRenderer RightTopFan3;
    ModelRenderer TopFan4;
    ModelRenderer TopFan5;
    ModelRenderer BottomLeftFan1;
    ModelRenderer BottomRightFan1;

    public ModelGlider2() {
        this.textureWidth = 128;
        this.textureHeight = 128;
        this.Shaft = new ModelRenderer(this, 0, 0);
        this.Shaft.addBox(0.0f, 0.0f, -21.0f, 1, 1, 42);
        this.Shaft.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Shaft.setTextureSize(128, 128);
        this.Shaft.mirror = true;
        this.setRotation(this.Shaft, 0.0f, 0.0f, 0.0f);
        this.NoduleTop = new ModelRenderer(this, 20, 4);
        this.NoduleTop.addBox(-1.0f, 0.0f, 0.0f, 3, 1, 1);
        this.NoduleTop.setRotationPoint(0.0f, 0.1f, -14.0f);
        this.NoduleTop.setTextureSize(128, 128);
        this.NoduleTop.mirror = true;
        this.setRotation(this.NoduleTop, 0.0f, 0.0f, 0.0f);
        this.NoduleBottom = new ModelRenderer(this, 20, 4);
        this.NoduleBottom.addBox(-1.0f, 0.0f, 0.0f, 3, 1, 1);
        this.NoduleBottom.setRotationPoint(0.0f, 0.1f, 13.0f);
        this.NoduleBottom.setTextureSize(128, 128);
        this.NoduleBottom.mirror = true;
        this.setRotation(this.NoduleBottom, 0.0f, 0.0f, 0.0f);
        this.TopLeftBar = new ModelRenderer(this, 0, 0);
        this.TopLeftBar.addBox(0.0f, 0.0f, 0.0f, 16, 1, 1);
        this.TopLeftBar.setRotationPoint(1.0f, 0.1f, -13.0f);
        this.TopLeftBar.setTextureSize(128, 128);
        this.TopLeftBar.mirror = true;
        this.setRotation(this.TopLeftBar, 0.0f, 0.0f, 0.0f);
        this.LeftBar1 = new ModelRenderer(this, 0, 0);
        this.LeftBar1.addBox(0.0f, 0.0f, 0.0f, 14, 1, 1);
        this.LeftBar1.setRotationPoint(1.0f, 0.2f, -12.0f);
        this.LeftBar1.setTextureSize(128, 128);
        this.LeftBar1.mirror = true;
        this.setRotation(this.LeftBar1, 0.0f, -0.3717861f, 0.0f);
        this.RightBar1 = new ModelRenderer(this, 0, 8);
        this.RightBar1.addBox(-14.0f, 0.0f, 0.0f, 14, 1, 1);
        this.RightBar1.setRotationPoint(0.0f, 0.2f, -12.0f);
        this.RightBar1.setTextureSize(128, 128);
        this.RightBar1.mirror = true;
        this.setRotation(this.RightBar1, 0.0f, 0.3717861f, 0.0f);
        this.LeftBar2 = new ModelRenderer(this, 0, 0);
        this.LeftBar2.addBox(0.0f, 0.0f, 0.0f, 12, 1, 1);
        this.LeftBar2.setRotationPoint(1.0f, 0.1f, -11.0f);
        this.LeftBar2.setTextureSize(128, 128);
        this.LeftBar2.mirror = true;
        this.setRotation(this.LeftBar2, 0.0f, -0.9666439f, 0.0f);
        this.RightBar2 = new ModelRenderer(this, 0, 0);
        this.RightBar2.addBox(-12.0f, 0.0f, 0.0f, 12, 1, 1);
        this.RightBar2.setRotationPoint(0.0f, 0.1f, -11.0f);
        this.RightBar2.setTextureSize(128, 128);
        this.RightBar2.mirror = true;
        this.setRotation(this.RightBar2, 0.0f, 0.9666439f, 0.0f);
        this.LeftBottomBar1 = new ModelRenderer(this, 0, 0);
        this.LeftBottomBar1.addBox(0.0f, 0.0f, 0.0f, 6, 1, 1);
        this.LeftBottomBar1.setRotationPoint(1.0f, 0.1f, 14.0f);
        this.LeftBottomBar1.setTextureSize(128, 128);
        this.LeftBottomBar1.mirror = true;
        this.setRotation(this.LeftBottomBar1, 0.0f, -0.5511566f, 0.0f);
        this.RightBottomBar2 = new ModelRenderer(this, 0, 0);
        this.RightBottomBar2.addBox(-7.0f, 0.0f, 0.0f, 7, 1, 1);
        this.RightBottomBar2.setRotationPoint(0.0f, 0.1f, 14.0f);
        this.RightBottomBar2.setTextureSize(128, 128);
        this.RightBottomBar2.mirror = true;
        this.setRotation(this.RightBottomBar2, 0.0f, 0.5511566f, 0.0f);
        this.LeftTopFan1 = new ModelRenderer(this, 0, 50);
        this.LeftTopFan1.addBox(0.0f, 0.0f, 0.0f, 15, 0, 6);
        this.LeftTopFan1.setRotationPoint(1.0f, 0.9f, -13.0f);
        this.LeftTopFan1.setTextureSize(128, 128);
        this.LeftTopFan1.mirror = true;
        this.setRotation(this.LeftTopFan1, 0.0f, -0.0367438f, 0.0f);
        this.RightTopFan1 = new ModelRenderer(this, 0, 50);
        this.RightTopFan1.addBox(-15.0f, 0.0f, 0.0f, 15, 0, 6);
        this.RightTopFan1.setRotationPoint(0.0f, 0.9f, -13.0f);
        this.RightTopFan1.setTextureSize(128, 128);
        this.RightTopFan1.mirror = true;
        this.setRotation(this.RightTopFan1, 0.0f, 0.0367392f, 0.0f);
        this.TopRightBar = new ModelRenderer(this, 0, 0);
        this.TopRightBar.addBox(-16.0f, 0.0f, 0.0f, 16, 1, 1);
        this.TopRightBar.setRotationPoint(0.0f, 0.1f, -13.0f);
        this.TopRightBar.setTextureSize(128, 128);
        this.TopRightBar.mirror = true;
        this.setRotation(this.TopRightBar, 0.0f, 0.0f, 0.0f);
        this.LeftTopFan2 = new ModelRenderer(this, 0, 50);
        this.LeftTopFan2.addBox(0.0f, 0.0f, 0.0f, 13, 0, 6);
        this.LeftTopFan2.setRotationPoint(3.0f, 0.8f, -12.0f);
        this.LeftTopFan2.setTextureSize(128, 128);
        this.LeftTopFan2.mirror = true;
        this.setRotation(this.LeftTopFan2, 0.0f, -0.4776691f, 0.0f);
        this.RightTopFan2 = new ModelRenderer(this, 0, 50);
        this.RightTopFan2.addBox(-13.0f, 0.0f, 0.0f, 13, 0, 6);
        this.RightTopFan2.setRotationPoint(-2.0f, 0.8f, -12.0f);
        this.RightTopFan2.setTextureSize(128, 128);
        this.RightTopFan2.mirror = true;
        this.setRotation(this.RightTopFan2, 0.0f, 0.4776617f, 0.0f);
        this.LeftTopFan3 = new ModelRenderer(this, 0, 50);
        this.LeftTopFan3.addBox(0.0f, 0.0f, 0.0f, 11, 0, 5);
        this.LeftTopFan3.setRotationPoint(3.0f, 0.7f, -9.0f);
        this.LeftTopFan3.setTextureSize(128, 128);
        this.LeftTopFan3.mirror = true;
        this.setRotation(this.LeftTopFan3, 0.0f, -0.808363f, 0.0f);
        this.RightTopFan3 = new ModelRenderer(this, 0, 50);
        this.RightTopFan3.addBox(-11.0f, 0.0f, 0.0f, 11, 0, 5);
        this.RightTopFan3.setRotationPoint(-2.0f, 0.7f, -9.0f);
        this.RightTopFan3.setTextureSize(128, 128);
        this.RightTopFan3.mirror = true;
        this.setRotation(this.RightTopFan3, 0.0f, 0.8083667f, 0.0f);
        this.TopFan4 = new ModelRenderer(this, 0, 50);
        this.TopFan4.addBox(-5.0f, 0.0f, 0.0f, 11, 0, 9);
        this.TopFan4.setRotationPoint(0.0f, 0.6f, -6.0f);
        this.TopFan4.setTextureSize(128, 128);
        this.TopFan4.mirror = true;
        this.setRotation(this.TopFan4, 0.0f, 0.0f, 0.0f);
        this.TopFan5 = new ModelRenderer(this, 0, 50);
        this.TopFan5.addBox(-3.0f, 0.0f, 0.0f, 7, 0, 1);
        this.TopFan5.setRotationPoint(0.0f, 0.6f, 3.0f);
        this.TopFan5.setTextureSize(128, 128);
        this.TopFan5.mirror = true;
        this.setRotation(this.TopFan5, 0.0f, 0.0f, 0.0f);
        this.BottomLeftFan1 = new ModelRenderer(this, 0, 50);
        this.BottomLeftFan1.addBox(0.0f, 0.0f, 0.0f, 5, 0, 3);
        this.BottomLeftFan1.setRotationPoint(1.0f, 0.9f, 15.0f);
        this.BottomLeftFan1.setTextureSize(128, 128);
        this.BottomLeftFan1.mirror = true;
        this.setRotation(this.BottomLeftFan1, 0.0f, -0.5144128f, 0.0f);
        this.BottomRightFan1 = new ModelRenderer(this, 0, 50);
        this.BottomRightFan1.addBox(-5.0f, 0.0f, 0.0f, 5, 0, 3);
        this.BottomRightFan1.setRotationPoint(0.0f, 0.9f, 15.0f);
        this.BottomRightFan1.setTextureSize(128, 128);
        this.BottomRightFan1.mirror = true;
        this.setRotation(this.BottomRightFan1, 0.0f, 0.5144183f, 0.0f);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        this.Shaft.render(f5);
        this.NoduleTop.render(f5);
        this.NoduleBottom.render(f5);
        this.TopLeftBar.render(f5);
        this.LeftBar1.render(f5);
        this.RightBar1.render(f5);
        this.LeftBar2.render(f5);
        this.RightBar2.render(f5);
        this.LeftBottomBar1.render(f5);
        this.RightBottomBar2.render(f5);
        this.LeftTopFan1.render(f5);
        this.RightTopFan1.render(f5);
        this.TopRightBar.render(f5);
        this.LeftTopFan2.render(f5);
        this.RightTopFan2.render(f5);
        this.LeftTopFan3.render(f5);
        this.RightTopFan3.render(f5);
        this.TopFan4.render(f5);
        this.TopFan5.render(f5);
        this.BottomLeftFan1.render(f5);
        this.BottomRightFan1.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
    }
}
