package com.voidsrift.riftflux.palaria.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.util.MathHelper;

import org.lwjgl.opengl.GL11;
import com.voidsrift.riftflux.palaria.entity.EntityNimatin;

public class ModelNimatin
extends ModelBase {
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightfrontleg1;
    ModelRenderer rightfrontleg2;
    ModelRenderer rightfrontfoot;
    ModelRenderer rightfrontclaw1;
    ModelRenderer rightfrontclaw2;
    ModelRenderer rightfrontclaw3;
    ModelRenderer leftfrontleg1;
    ModelRenderer leftfrontleg2;
    ModelRenderer leftfrontfoot;
    ModelRenderer leftfrontclaw1;
    ModelRenderer leftfrontclaw2;
    ModelRenderer leftfrontclaw3;
    ModelRenderer rightbackleg1;
    ModelRenderer rightbackleg2;
    ModelRenderer rightbackleg3;
    ModelRenderer rightbackfoot;
    ModelRenderer rightbackclaw1;
    ModelRenderer rightbackclaw2;
    ModelRenderer rightbackclaw3;
    ModelRenderer leftbackleg1;
    ModelRenderer leftbackleg2;
    ModelRenderer leftbackleg3;
    ModelRenderer leftbackfoot;
    ModelRenderer leftbackclaw1;
    ModelRenderer leftbackclaw2;
    ModelRenderer leftbackclaw3;
    ModelRenderer tail1;
    ModelRenderer tail2;
    ModelRenderer tail3;
    ModelRenderer tail4;
    ModelRenderer tail5;
    ModelRenderer jaw;
    ModelRenderer nose;
    ModelRenderer tooth1;
    ModelRenderer tooth2;
    ModelRenderer tooth3;
    ModelRenderer tooth4;

    public ModelNimatin() {
        this.textureWidth = 256;
        this.textureHeight = 256;
        if (this.isChild) {
            this.head = new ModelRenderer(this, 0, 31);
            this.head.addBox(-8.0f, -5.0f, -9.0f, 16, 14, 16);
            this.head.setRotationPoint(-1.0f, 0.0f, -24.0f);
            this.head.setTextureSize(256, 256);
            this.head.mirror = true;
            this.setRotation(this.head, 0.0f, 0.0f, 0.0f);
            this.body = new ModelRenderer(this, 32, 68);
            this.body.addBox(0.0f, 0.0f, 0.0f, 14, 16, 45);
            this.body.setRotationPoint(-8.0f, -1.0f, -24.0f);
            this.body.setTextureSize(256, 256);
            this.body.mirror = true;
            this.setRotation(this.body, 0.0f, 0.0f, 0.0f);
            this.rightfrontleg1 = new ModelRenderer(this, 0, 61);
            this.rightfrontleg1.addBox(-4.0f, -2.0f, -4.0f, 7, 12, 7);
            this.rightfrontleg1.setRotationPoint(-9.0f, -1.0f, -12.0f);
            this.rightfrontleg1.setTextureSize(256, 256);
            this.rightfrontleg1.mirror = true;
            this.setRotation(this.rightfrontleg1, 0.0f, 0.0f, 0.0f);
            this.rightfrontleg2 = new ModelRenderer(this, 0, 80);
            this.rightfrontleg2.addBox(-3.9f, 6.0f, -2.0f, 7, 16, 6);
            this.rightfrontleg2.setRotationPoint(-9.0f, -1.0f, -12.0f);
            this.rightfrontleg2.setTextureSize(256, 256);
            this.rightfrontleg2.mirror = true;
            this.setRotation(this.rightfrontleg2, 0.0f, 0.0f, 0.0f);
            this.rightfrontfoot = new ModelRenderer(this, 0, 102);
            this.rightfrontfoot.addBox(-4.0f, 21.0f, -5.0f, 7, 3, 9);
            this.rightfrontfoot.setRotationPoint(-9.0f, 0.0f, -12.0f);
            this.rightfrontfoot.setTextureSize(256, 256);
            this.rightfrontfoot.mirror = true;
            this.setRotation(this.rightfrontfoot, 0.0f, 0.0f, 0.0f);
            this.rightfrontclaw1 = new ModelRenderer(this, 0, 114);
            this.rightfrontclaw1.addBox(1.0f, 23.0f, -7.0f, 1, 2, 3);
            this.rightfrontclaw1.setRotationPoint(-9.0f, -1.0f, -12.0f);
            this.rightfrontclaw1.setTextureSize(256, 256);
            this.rightfrontclaw1.mirror = true;
            this.setRotation(this.rightfrontclaw1, 0.0f, 0.0f, 0.0f);
            this.rightfrontclaw2 = new ModelRenderer(this, 0, 119);
            this.rightfrontclaw2.addBox(-1.0f, 23.0f, -8.0f, 1, 2, 4);
            this.rightfrontclaw2.setRotationPoint(-9.0f, -1.0f, -12.0f);
            this.rightfrontclaw2.setTextureSize(256, 256);
            this.rightfrontclaw2.mirror = true;
            this.setRotation(this.rightfrontclaw2, 0.0f, 0.0f, 0.0f);
            this.rightfrontclaw3 = new ModelRenderer(this, 0, 114);
            this.rightfrontclaw3.addBox(-3.0f, 23.0f, -7.0f, 1, 2, 3);
            this.rightfrontclaw3.setRotationPoint(-9.0f, -1.0f, -12.0f);
            this.rightfrontclaw3.setTextureSize(256, 256);
            this.rightfrontclaw3.mirror = true;
            this.setRotation(this.rightfrontclaw3, 0.0f, 0.0f, 0.0f);
            this.leftfrontleg1 = new ModelRenderer(this, 0, 61);
            this.leftfrontleg1.addBox(-4.0f, -2.0f, -4.0f, 7, 12, 7);
            this.leftfrontleg1.setRotationPoint(7.0f, -1.0f, -12.0f);
            this.leftfrontleg1.setTextureSize(256, 256);
            this.leftfrontleg1.mirror = true;
            this.setRotation(this.leftfrontleg1, 0.0f, 0.0f, 0.0f);
            this.leftfrontleg2 = new ModelRenderer(this, 0, 80);
            this.leftfrontleg2.addBox(-3.9f, 6.0f, -2.0f, 7, 16, 6);
            this.leftfrontleg2.setRotationPoint(7.0f, -1.0f, -12.0f);
            this.leftfrontleg2.setTextureSize(256, 256);
            this.leftfrontleg2.mirror = true;
            this.setRotation(this.leftfrontleg2, 0.0f, 0.0f, 0.0f);
            this.leftfrontfoot = new ModelRenderer(this, 0, 102);
            this.leftfrontfoot.addBox(-4.0f, 21.0f, -3.0f, 7, 3, 9);
            this.leftfrontfoot.setRotationPoint(7.0f, 0.0f, -14.0f);
            this.leftfrontfoot.setTextureSize(256, 256);
            this.leftfrontfoot.mirror = true;
            this.setRotation(this.leftfrontfoot, 0.0f, 0.0f, 0.0f);
            this.leftfrontclaw1 = new ModelRenderer(this, 0, 114);
            this.leftfrontclaw1.addBox(1.0f, 23.0f, -7.0f, 1, 2, 3);
            this.leftfrontclaw1.setRotationPoint(7.0f, -1.0f, -12.0f);
            this.leftfrontclaw1.setTextureSize(256, 256);
            this.leftfrontclaw1.mirror = true;
            this.setRotation(this.leftfrontclaw1, 0.0f, 0.0f, 0.0f);
            this.leftfrontclaw2 = new ModelRenderer(this, 0, 119);
            this.leftfrontclaw2.addBox(-1.0f, 23.0f, -8.0f, 1, 2, 4);
            this.leftfrontclaw2.setRotationPoint(7.0f, -1.0f, -12.0f);
            this.leftfrontclaw2.setTextureSize(256, 256);
            this.leftfrontclaw2.mirror = true;
            this.setRotation(this.leftfrontclaw2, 0.0f, 0.0f, 0.0f);
            this.leftfrontclaw3 = new ModelRenderer(this, 0, 114);
            this.leftfrontclaw3.addBox(-3.0f, 23.0f, -7.0f, 1, 2, 3);
            this.leftfrontclaw3.setRotationPoint(7.0f, -1.0f, -12.0f);
            this.leftfrontclaw3.setTextureSize(256, 256);
            this.leftfrontclaw3.mirror = true;
            this.setRotation(this.leftfrontclaw3, 0.0f, 0.0f, 0.0f);
            this.rightbackleg1 = new ModelRenderer(this, 28, 61);
            this.rightbackleg1.addBox(-4.0f, -2.0f, -2.0f, 7, 12, 8);
            this.rightbackleg1.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.rightbackleg1.setTextureSize(256, 256);
            this.rightbackleg1.mirror = true;
            this.setRotation(this.rightbackleg1, 0.0f, 0.0f, 0.0f);
            this.rightbackleg2 = new ModelRenderer(this, 30, 81);
            this.rightbackleg2.addBox(-3.9f, 6.0f, -1.5f, 7, 8, 7);
            this.rightbackleg2.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.rightbackleg2.setTextureSize(256, 256);
            this.rightbackleg2.mirror = true;
            this.setRotation(this.rightbackleg2, 0.0f, 0.0f, 0.0f);
            this.rightbackleg3 = new ModelRenderer(this, 32, 96);
            this.rightbackleg3.addBox(-4.0f, 13.0f, -1.0f, 7, 11, 6);
            this.rightbackleg3.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.rightbackleg3.setTextureSize(256, 256);
            this.rightbackleg3.mirror = true;
            this.setRotation(this.rightbackleg3, 0.0f, 0.0f, 0.0f);
            this.rightbackfoot = new ModelRenderer(this, 0, 102);
            this.rightbackfoot.addBox(-4.0f, 22.0f, -4.0f, 7, 3, 9);
            this.rightbackfoot.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.rightbackfoot.setTextureSize(256, 256);
            this.rightbackfoot.mirror = true;
            this.setRotation(this.rightbackfoot, 0.0f, 0.0f, 0.0f);
            this.rightbackclaw1 = new ModelRenderer(this, 0, 114);
            this.rightbackclaw1.addBox(-3.0f, 23.0f, -6.0f, 1, 2, 3);
            this.rightbackclaw1.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.rightbackclaw1.setTextureSize(256, 256);
            this.rightbackclaw1.mirror = true;
            this.setRotation(this.rightbackclaw1, 0.0f, 0.0f, 0.0f);
            this.rightbackclaw2 = new ModelRenderer(this, 0, 114);
            this.rightbackclaw2.addBox(1.0f, 23.0f, -6.0f, 1, 2, 3);
            this.rightbackclaw2.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.rightbackclaw2.setTextureSize(256, 256);
            this.rightbackclaw2.mirror = true;
            this.setRotation(this.rightbackclaw2, 0.0f, 0.0f, 0.0f);
            this.rightbackclaw3 = new ModelRenderer(this, 0, 119);
            this.rightbackclaw3.addBox(-1.0f, 23.0f, -7.0f, 1, 2, 4);
            this.rightbackclaw3.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.rightbackclaw3.setTextureSize(256, 256);
            this.rightbackclaw3.mirror = true;
            this.setRotation(this.rightbackclaw3, 0.0f, 0.0f, 0.0f);
            this.leftbackleg1 = new ModelRenderer(this, 28, 61);
            this.leftbackleg1.addBox(-4.0f, -2.0f, -2.0f, 7, 12, 8);
            this.leftbackleg1.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.leftbackleg1.setTextureSize(256, 256);
            this.leftbackleg1.mirror = true;
            this.setRotation(this.leftbackleg1, 0.0f, 0.0f, 0.0f);
            this.leftbackleg2 = new ModelRenderer(this, 30, 81);
            this.leftbackleg2.addBox(-3.9f, 6.0f, -1.5f, 7, 8, 7);
            this.leftbackleg2.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.leftbackleg2.setTextureSize(256, 256);
            this.leftbackleg2.mirror = true;
            this.setRotation(this.leftbackleg2, 0.0f, 0.0f, 0.0f);
            this.leftbackleg3 = new ModelRenderer(this, 32, 96);
            this.leftbackleg3.addBox(-4.0f, 13.0f, -1.0f, 7, 11, 6);
            this.leftbackleg3.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.leftbackleg3.setTextureSize(256, 256);
            this.leftbackleg3.mirror = true;
            this.setRotation(this.leftbackleg3, 0.0f, 0.0f, 0.0f);
            this.leftbackfoot = new ModelRenderer(this, 0, 102);
            this.leftbackfoot.addBox(-4.0f, 22.0f, -4.0f, 7, 3, 9);
            this.leftbackfoot.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.leftbackfoot.setTextureSize(256, 256);
            this.leftbackfoot.mirror = true;
            this.setRotation(this.leftbackfoot, 0.0f, 0.0f, 0.0f);
            this.leftbackclaw1 = new ModelRenderer(this, 0, 114);
            this.leftbackclaw1.addBox(-3.0f, 23.0f, -6.0f, 1, 2, 3);
            this.leftbackclaw1.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.leftbackclaw1.setTextureSize(256, 256);
            this.leftbackclaw1.mirror = true;
            this.setRotation(this.leftbackclaw1, 0.0f, 0.0f, 0.0f);
            this.leftbackclaw2 = new ModelRenderer(this, 0, 114);
            this.leftbackclaw2.addBox(1.0f, 23.0f, -6.0f, 1, 2, 3);
            this.leftbackclaw2.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.leftbackclaw2.setTextureSize(256, 256);
            this.leftbackclaw2.mirror = true;
            this.setRotation(this.leftbackclaw2, 0.0f, 0.0f, 0.0f);
            this.leftbackclaw3 = new ModelRenderer(this, 0, 119);
            this.leftbackclaw3.addBox(-1.0f, 23.0f, -7.0f, 1, 2, 4);
            this.leftbackclaw3.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.leftbackclaw3.setTextureSize(256, 256);
            this.leftbackclaw3.mirror = true;
            this.setRotation(this.leftbackclaw3, 0.0f, 0.0f, 0.0f);
            this.tail1 = new ModelRenderer(this, 56, 53);
            this.tail1.addBox(-3.0f, 0.0f, 0.0f, 6, 6, 8);
            this.tail1.setRotationPoint(-1.0f, 0.0f, 21.0f);
            this.tail1.setTextureSize(256, 256);
            this.tail1.mirror = true;
            this.setRotation(this.tail1, -0.4363323f, 0.0f, 0.0f);
            this.tail2 = new ModelRenderer(this, 56, 53);
            this.tail2.addBox(-3.0f, 0.0f, 8.0f, 6, 6, 8);
            this.tail2.setRotationPoint(-1.0f, 0.0f, 21.0f);
            this.tail2.setTextureSize(256, 256);
            this.tail2.mirror = true;
            this.setRotation(this.tail2, -0.4363323f, 0.0f, 0.0f);
            this.tail3 = new ModelRenderer(this, 84, 54);
            this.tail3.addBox(-2.5f, 8.0f, 11.0f, 5, 5, 8);
            this.tail3.setRotationPoint(-1.0f, 0.0f, 21.0f);
            this.tail3.setTextureSize(256, 256);
            this.tail3.mirror = true;
            this.setRotation(this.tail3, 0.0872665f, 0.0f, 0.0f);
            this.tail4 = new ModelRenderer(this, 110, 53);
            this.tail4.addBox(-2.5f, 8.0f, 19.0f, 5, 5, 9);
            this.tail4.setRotationPoint(-1.0f, 0.0f, 21.0f);
            this.tail4.setTextureSize(256, 256);
            this.tail4.mirror = true;
            this.setRotation(this.tail4, 0.0872665f, 0.0f, 0.0f);
            this.tail5 = new ModelRenderer(this, 138, 53);
            this.tail5.addBox(-2.5f, 8.0f, 27.0f, 5, 5, 9);
            this.tail5.setRotationPoint(-1.0f, 0.0f, 21.0f);
            this.tail5.setTextureSize(256, 256);
            this.tail5.mirror = true;
            this.setRotation(this.tail5, 0.0872665f, 0.0f, 0.0f);
            this.jaw = new ModelRenderer(this, 51, 29);
            this.jaw.addBox(-6.0f, 7.0f, -21.0f, 12, 2, 16);
            this.jaw.setRotationPoint(-1.0f, 0.0f, -24.0f);
            this.jaw.setTextureSize(256, 256);
            this.jaw.mirror = true;
            this.setRotation(this.jaw, 0.0f, 0.0f, 0.0f);
            this.nose = new ModelRenderer(this, 50, 130);
            this.nose.addBox(-6.0f, 2.0f, -21.0f, 12, 5, 16);
            this.nose.setRotationPoint(-1.0f, 0.0f, -24.0f);
            this.nose.setTextureSize(256, 256);
            this.nose.mirror = true;
            this.setRotation(this.nose, 0.0f, 0.0f, 0.0f);
            this.tooth1 = new ModelRenderer(this, 15, 15);
            this.tooth1.addBox(-7.0f, 0.0f, -21.0f, 2, 6, 2);
            this.tooth1.setRotationPoint(-1.0f, 10.0f, -24.0f);
            this.tooth1.setTextureSize(256, 256);
            this.tooth1.mirror = true;
            this.setRotation(this.tooth1, 0.0f, 0.0f, 0.0f);
            this.tooth2 = new ModelRenderer(this, 15, 15);
            this.tooth2.addBox(5.0f, 0.0f, -21.0f, 2, 6, 2);
            this.tooth2.setRotationPoint(-1.0f, 10.0f, -24.0f);
            this.tooth2.setTextureSize(256, 256);
            this.tooth2.mirror = true;
            this.setRotation(this.tooth2, 0.0f, 0.0f, 0.0f);
            this.tooth3 = new ModelRenderer(this, 11, 20);
            this.tooth3.addBox(-5.0f, 5.0f, -20.0f, 1, 2, 1);
            this.tooth3.setRotationPoint(-1.0f, 0.0f, -24.0f);
            this.tooth3.setTextureSize(256, 256);
            this.tooth3.mirror = true;
            this.setRotation(this.tooth3, 0.0f, 0.0f, 0.0f);
            this.tooth4 = new ModelRenderer(this, 11, 20);
            this.tooth4.addBox(4.0f, 5.0f, -20.0f, 1, 2, 1);
            this.tooth4.setRotationPoint(-1.0f, 0.0f, -24.0f);
            this.tooth4.setTextureSize(256, 256);
            this.tooth4.mirror = true;
            this.setRotation(this.tooth4, 0.0f, 0.0f, 0.0f);
        } else {
            this.head = new ModelRenderer(this, 0, 31);
            this.head.addBox(-8.0f, -7.0f, -16.0f, 16, 14, 16);
            this.head.setRotationPoint(-1.0f, 0.0f, -24.0f);
            this.head.setTextureSize(256, 256);
            this.head.mirror = true;
            this.setRotation(this.head, 0.0f, 0.0f, 0.0f);
            this.body = new ModelRenderer(this, 32, 68);
            this.body.addBox(0.0f, 0.0f, 0.0f, 14, 16, 45);
            this.body.setRotationPoint(-8.0f, -1.0f, -24.0f);
            this.body.setTextureSize(256, 256);
            this.body.mirror = true;
            this.setRotation(this.body, 0.0f, 0.0f, 0.0f);
            this.rightfrontleg1 = new ModelRenderer(this, 0, 61);
            this.rightfrontleg1.addBox(-4.0f, -2.0f, -4.0f, 7, 12, 7);
            this.rightfrontleg1.setRotationPoint(-9.0f, -1.0f, -12.0f);
            this.rightfrontleg1.setTextureSize(256, 256);
            this.rightfrontleg1.mirror = true;
            this.setRotation(this.rightfrontleg1, 0.0f, 0.0f, 0.0f);
            this.rightfrontleg2 = new ModelRenderer(this, 0, 80);
            this.rightfrontleg2.addBox(-3.9f, 6.0f, -2.0f, 7, 16, 6);
            this.rightfrontleg2.setRotationPoint(-9.0f, -1.0f, -12.0f);
            this.rightfrontleg2.setTextureSize(256, 256);
            this.rightfrontleg2.mirror = true;
            this.setRotation(this.rightfrontleg2, 0.0f, 0.0f, 0.0f);
            this.rightfrontfoot = new ModelRenderer(this, 0, 102);
            this.rightfrontfoot.addBox(-4.0f, 21.0f, -5.0f, 7, 3, 9);
            this.rightfrontfoot.setRotationPoint(-9.0f, 0.0f, -12.0f);
            this.rightfrontfoot.setTextureSize(256, 256);
            this.rightfrontfoot.mirror = true;
            this.setRotation(this.rightfrontfoot, 0.0f, 0.0f, 0.0f);
            this.rightfrontclaw1 = new ModelRenderer(this, 0, 114);
            this.rightfrontclaw1.addBox(1.0f, 23.0f, -7.0f, 1, 2, 3);
            this.rightfrontclaw1.setRotationPoint(-9.0f, -1.0f, -12.0f);
            this.rightfrontclaw1.setTextureSize(256, 256);
            this.rightfrontclaw1.mirror = true;
            this.setRotation(this.rightfrontclaw1, 0.0f, 0.0f, 0.0f);
            this.rightfrontclaw2 = new ModelRenderer(this, 0, 119);
            this.rightfrontclaw2.addBox(-1.0f, 23.0f, -8.0f, 1, 2, 4);
            this.rightfrontclaw2.setRotationPoint(-9.0f, -1.0f, -12.0f);
            this.rightfrontclaw2.setTextureSize(256, 256);
            this.rightfrontclaw2.mirror = true;
            this.setRotation(this.rightfrontclaw2, 0.0f, 0.0f, 0.0f);
            this.rightfrontclaw3 = new ModelRenderer(this, 0, 114);
            this.rightfrontclaw3.addBox(-3.0f, 23.0f, -7.0f, 1, 2, 3);
            this.rightfrontclaw3.setRotationPoint(-9.0f, -1.0f, -12.0f);
            this.rightfrontclaw3.setTextureSize(256, 256);
            this.rightfrontclaw3.mirror = true;
            this.setRotation(this.rightfrontclaw3, 0.0f, 0.0f, 0.0f);
            this.leftfrontleg1 = new ModelRenderer(this, 0, 61);
            this.leftfrontleg1.addBox(-4.0f, -2.0f, -7.0f, 7, 12, 7);
            this.leftfrontleg1.setRotationPoint(7.0f, -1.0f, -12.0f);
            this.leftfrontleg1.setTextureSize(256, 256);
            this.leftfrontleg1.mirror = true;
            this.setRotation(this.leftfrontleg1, 0.0f, 0.0f, 0.0f);
            this.leftfrontleg2 = new ModelRenderer(this, 0, 80);
            this.leftfrontleg2.addBox(-3.9f, 6.0f, -2.0f, 7, 16, 6);
            this.leftfrontleg2.setRotationPoint(7.0f, -1.0f, -12.0f);
            this.leftfrontleg2.setTextureSize(256, 256);
            this.leftfrontleg2.mirror = true;
            this.setRotation(this.leftfrontleg2, 0.0f, 0.0f, 0.0f);
            this.leftfrontfoot = new ModelRenderer(this, 0, 102);
            this.leftfrontfoot.addBox(-4.0f, 21.0f, -3.0f, 7, 3, 9);
            this.leftfrontfoot.setRotationPoint(7.0f, 0.0f, -14.0f);
            this.leftfrontfoot.setTextureSize(256, 256);
            this.leftfrontfoot.mirror = true;
            this.setRotation(this.leftfrontfoot, 0.0f, 0.0f, 0.0f);
            this.leftfrontclaw1 = new ModelRenderer(this, 0, 114);
            this.leftfrontclaw1.addBox(1.0f, 23.0f, -7.0f, 1, 2, 3);
            this.leftfrontclaw1.setRotationPoint(7.0f, -1.0f, -12.0f);
            this.leftfrontclaw1.setTextureSize(256, 256);
            this.leftfrontclaw1.mirror = true;
            this.setRotation(this.leftfrontclaw1, 0.0f, 0.0f, 0.0f);
            this.leftfrontclaw2 = new ModelRenderer(this, 0, 119);
            this.leftfrontclaw2.addBox(-1.0f, 23.0f, -8.0f, 1, 2, 4);
            this.leftfrontclaw2.setRotationPoint(7.0f, -1.0f, -12.0f);
            this.leftfrontclaw2.setTextureSize(256, 256);
            this.leftfrontclaw2.mirror = true;
            this.setRotation(this.leftfrontclaw2, 0.0f, 0.0f, 0.0f);
            this.leftfrontclaw3 = new ModelRenderer(this, 0, 114);
            this.leftfrontclaw3.addBox(-3.0f, 23.0f, -7.0f, 1, 2, 3);
            this.leftfrontclaw3.setRotationPoint(7.0f, -1.0f, -12.0f);
            this.leftfrontclaw3.setTextureSize(256, 256);
            this.leftfrontclaw3.mirror = true;
            this.setRotation(this.leftfrontclaw3, 0.0f, 0.0f, 0.0f);
            this.rightbackleg1 = new ModelRenderer(this, 28, 61);
            this.rightbackleg1.addBox(-4.0f, -2.0f, -2.0f, 7, 12, 8);
            this.rightbackleg1.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.rightbackleg1.setTextureSize(256, 256);
            this.rightbackleg1.mirror = true;
            this.setRotation(this.rightbackleg1, 0.0f, 0.0f, 0.0f);
            this.rightbackleg2 = new ModelRenderer(this, 30, 81);
            this.rightbackleg2.addBox(-3.9f, 6.0f, -1.5f, 7, 8, 7);
            this.rightbackleg2.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.rightbackleg2.setTextureSize(256, 256);
            this.rightbackleg2.mirror = true;
            this.setRotation(this.rightbackleg2, 0.0f, 0.0f, 0.0f);
            this.rightbackleg3 = new ModelRenderer(this, 32, 96);
            this.rightbackleg3.addBox(-4.0f, 13.0f, -1.0f, 7, 11, 6);
            this.rightbackleg3.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.rightbackleg3.setTextureSize(256, 256);
            this.rightbackleg3.mirror = true;
            this.setRotation(this.rightbackleg3, 0.0f, 0.0f, 0.0f);
            this.rightbackfoot = new ModelRenderer(this, 0, 102);
            this.rightbackfoot.addBox(-4.0f, 22.0f, -4.0f, 7, 3, 9);
            this.rightbackfoot.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.rightbackfoot.setTextureSize(256, 256);
            this.rightbackfoot.mirror = true;
            this.setRotation(this.rightbackfoot, 0.0f, 0.0f, 0.0f);
            this.rightbackclaw1 = new ModelRenderer(this, 0, 114);
            this.rightbackclaw1.addBox(-3.0f, 23.0f, -6.0f, 1, 2, 3);
            this.rightbackclaw1.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.rightbackclaw1.setTextureSize(256, 256);
            this.rightbackclaw1.mirror = true;
            this.setRotation(this.rightbackclaw1, 0.0f, 0.0f, 0.0f);
            this.rightbackclaw2 = new ModelRenderer(this, 0, 114);
            this.rightbackclaw2.addBox(1.0f, 23.0f, -6.0f, 1, 2, 3);
            this.rightbackclaw2.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.rightbackclaw2.setTextureSize(256, 256);
            this.rightbackclaw2.mirror = true;
            this.setRotation(this.rightbackclaw2, 0.0f, 0.0f, 0.0f);
            this.rightbackclaw3 = new ModelRenderer(this, 0, 119);
            this.rightbackclaw3.addBox(-1.0f, 23.0f, -7.0f, 1, 2, 4);
            this.rightbackclaw3.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.rightbackclaw3.setTextureSize(256, 256);
            this.rightbackclaw3.mirror = true;
            this.setRotation(this.rightbackclaw3, 0.0f, 0.0f, 0.0f);
            this.leftbackleg1 = new ModelRenderer(this, 28, 61);
            this.leftbackleg1.addBox(-4.0f, -2.0f, 0.0f, 7, 12, 8);
            this.leftbackleg1.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.leftbackleg1.setTextureSize(256, 256);
            this.leftbackleg1.mirror = true;
            this.setRotation(this.leftbackleg1, 0.0f, 0.0f, 0.0f);
            this.leftbackleg2 = new ModelRenderer(this, 30, 81);
            this.leftbackleg2.addBox(-4.0f, 3.0f, -13.0f, 7, 8, 7);
            this.leftbackleg2.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.leftbackleg2.setTextureSize(256, 256);
            this.leftbackleg2.mirror = true;
            this.setRotation(this.leftbackleg2, 0.6981317f, 0.0f, 0.0f);
            this.leftbackleg3 = new ModelRenderer(this, 32, 96);
            this.leftbackleg3.addBox(-4.0f, 13.0f, -1.0f, 7, 11, 6);
            this.leftbackleg3.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.leftbackleg3.setTextureSize(256, 256);
            this.leftbackleg3.mirror = true;
            this.setRotation(this.leftbackleg3, -0.1745329f, 0.0f, 0.0f);
            this.leftbackfoot = new ModelRenderer(this, 0, 102);
            this.leftbackfoot.addBox(-4.0f, 22.0f, -8.0f, 7, 3, 9);
            this.leftbackfoot.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.leftbackfoot.setTextureSize(256, 256);
            this.leftbackfoot.mirror = true;
            this.setRotation(this.leftbackfoot, 0.0f, 0.0f, 0.0f);
            this.leftbackclaw1 = new ModelRenderer(this, 0, 114);
            this.leftbackclaw1.addBox(-3.0f, 23.0f, -10.0f, 1, 2, 3);
            this.leftbackclaw1.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.leftbackclaw1.setTextureSize(256, 256);
            this.leftbackclaw1.mirror = true;
            this.setRotation(this.leftbackclaw1, 0.0f, 0.0f, 0.0f);
            this.leftbackclaw2 = new ModelRenderer(this, 0, 114);
            this.leftbackclaw2.addBox(1.0f, 23.0f, -10.0f, 1, 2, 3);
            this.leftbackclaw2.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.leftbackclaw2.setTextureSize(256, 256);
            this.leftbackclaw2.mirror = true;
            this.setRotation(this.leftbackclaw2, 0.0f, 0.0f, 0.0f);
            this.leftbackclaw3 = new ModelRenderer(this, 0, 119);
            this.leftbackclaw3.addBox(-1.0f, 23.0f, -11.0f, 1, 2, 4);
            this.leftbackclaw3.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.leftbackclaw3.setTextureSize(256, 256);
            this.leftbackclaw3.mirror = true;
            this.setRotation(this.leftbackclaw3, 0.0f, 0.0f, 0.0f);
            this.tail1 = new ModelRenderer(this, 56, 53);
            this.tail1.addBox(-3.0f, 0.0f, 0.0f, 6, 6, 8);
            this.tail1.setRotationPoint(-1.0f, 0.0f, 21.0f);
            this.tail1.setTextureSize(256, 256);
            this.tail1.mirror = true;
            this.setRotation(this.tail1, -0.4363323f, 0.0f, 0.0f);
            this.tail2 = new ModelRenderer(this, 56, 53);
            this.tail2.addBox(-3.0f, 0.0f, 8.0f, 6, 6, 8);
            this.tail2.setRotationPoint(-1.0f, 0.0f, 21.0f);
            this.tail2.setTextureSize(256, 256);
            this.tail2.mirror = true;
            this.setRotation(this.tail2, -0.4363323f, 0.0f, 0.0f);
            this.tail3 = new ModelRenderer(this, 84, 54);
            this.tail3.addBox(-2.5f, 8.0f, 11.0f, 5, 5, 8);
            this.tail3.setRotationPoint(-1.0f, 0.0f, 21.0f);
            this.tail3.setTextureSize(256, 256);
            this.tail3.mirror = true;
            this.setRotation(this.tail3, 0.0872665f, 0.0f, 0.0f);
            this.tail4 = new ModelRenderer(this, 110, 53);
            this.tail4.addBox(-2.5f, 8.0f, 19.0f, 5, 5, 9);
            this.tail4.setRotationPoint(-1.0f, 0.0f, 21.0f);
            this.tail4.setTextureSize(256, 256);
            this.tail4.mirror = true;
            this.setRotation(this.tail4, 0.0872665f, 0.0f, 0.0f);
            this.tail5 = new ModelRenderer(this, 138, 53);
            this.tail5.addBox(-2.5f, 8.0f, 27.0f, 5, 5, 9);
            this.tail5.setRotationPoint(-1.0f, 0.0f, 21.0f);
            this.tail5.setTextureSize(256, 256);
            this.tail5.mirror = true;
            this.setRotation(this.tail5, 0.0872665f, 0.0f, 0.0f);
            this.jaw = new ModelRenderer(this, 51, 29);
            this.jaw.addBox(-6.0f, 5.0f, -28.0f, 12, 2, 16);
            this.jaw.setRotationPoint(-1.0f, 0.0f, -24.0f);
            this.jaw.setTextureSize(256, 256);
            this.jaw.mirror = true;
            this.setRotation(this.jaw, 0.0f, 0.0f, 0.0f);
            this.nose = new ModelRenderer(this, 50, 130);
            this.nose.addBox(-6.0f, 0.0f, -28.0f, 12, 5, 16);
            this.nose.setRotationPoint(-1.0f, 0.0f, -24.0f);
            this.nose.setTextureSize(256, 256);
            this.nose.mirror = true;
            this.setRotation(this.nose, 0.0f, 0.0f, 0.0f);
            this.tooth1 = new ModelRenderer(this, 15, 15);
            this.tooth1.addBox(-7.0f, -5.0f, -28.0f, 2, 6, 2);
            this.tooth1.setRotationPoint(-1.0f, 0.0f, -24.0f);
            this.tooth1.setTextureSize(256, 256);
            this.tooth1.mirror = true;
            this.setRotation(this.tooth1, 0.3490659f, 0.0f, 0.0f);
            this.tooth2 = new ModelRenderer(this, 15, 15);
            this.tooth2.addBox(5.0f, -5.0f, -28.0f, 2, 6, 2);
            this.tooth2.setRotationPoint(-1.0f, 0.0f, -24.0f);
            this.tooth2.setTextureSize(256, 256);
            this.tooth2.mirror = true;
            this.setRotation(this.tooth2, 0.3490659f, 0.0f, 0.0f);
            this.tooth3 = new ModelRenderer(this, 11, 20);
            this.tooth3.addBox(-5.0f, 3.0f, -27.0f, 1, 2, 1);
            this.tooth3.setRotationPoint(-1.0f, 0.0f, -24.0f);
            this.tooth3.setTextureSize(256, 256);
            this.tooth3.mirror = true;
            this.setRotation(this.tooth3, 0.0f, 0.0f, 0.0f);
            this.tooth4 = new ModelRenderer(this, 11, 20);
            this.tooth4.addBox(4.0f, 3.0f, -27.0f, 1, 2, 1);
            this.tooth4.setRotationPoint(-1.0f, 0.0f, -24.0f);
            this.tooth4.setTextureSize(256, 256);
            this.tooth4.mirror = true;
            this.setRotation(this.tooth4, 0.0f, 0.0f, 0.0f);
        }
    }

    public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7) {
        super.render(par1Entity, par2, par3, par4, par5, par6, par7);
        this.setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
        GL11.glPushMatrix();
        GL11.glTranslatef(par7, 0.0f, 0.0f);
        if (this.isChild) {
            float var8 = 2.0f;
            GL11.glPushMatrix();
            GL11.glScalef((float)(1.5f / var8), (float)(1.5f / var8), (float)(1.5f / var8));
            GL11.glTranslatef((float)0.0f, (float)(10.0f * par7), (float)(4.0f * par7));
            this.head.render(par7);
            this.jaw.render(par7);
            this.nose.render(par7);
            this.tooth1.render(par7);
            this.tooth2.render(par7);
            this.tooth3.render(par7);
            this.tooth4.render(par7);
            GL11.glPopMatrix();
            GL11.glPushMatrix();
            GL11.glScalef((float)(1.0f / var8), (float)(1.0f / var8), (float)(1.0f / var8));
            GL11.glTranslatef((float)0.0f, (float)(24.0f * par7), (float)0.0f);
            this.body.render(par7);
            this.rightfrontleg1.render(par7);
            this.rightfrontleg2.render(par7);
            this.rightfrontfoot.render(par7);
            this.rightfrontclaw1.render(par7);
            this.rightfrontclaw2.render(par7);
            this.rightfrontclaw3.render(par7);
            this.leftfrontleg1.render(par7);
            this.leftfrontleg2.render(par7);
            this.leftfrontfoot.render(par7);
            this.leftfrontclaw1.render(par7);
            this.leftfrontclaw2.render(par7);
            this.leftfrontclaw3.render(par7);
            this.rightbackleg1.render(par7);
            this.rightbackleg2.render(par7);
            this.rightbackleg3.render(par7);
            this.rightbackfoot.render(par7);
            this.rightbackclaw1.render(par7);
            this.rightbackclaw2.render(par7);
            this.rightbackclaw3.render(par7);
            this.leftbackleg1.render(par7);
            this.leftbackleg2.render(par7);
            this.leftbackleg3.render(par7);
            this.leftbackfoot.render(par7);
            this.leftbackclaw1.render(par7);
            this.leftbackclaw2.render(par7);
            this.leftbackclaw3.render(par7);
            this.tail1.render(par7);
            this.tail2.render(par7);
            this.tail3.render(par7);
            this.tail4.render(par7);
            this.tail5.render(par7);
            GL11.glPopMatrix();
        } else {
            this.head.render(par7);
            this.body.render(par7);
            this.rightfrontleg1.render(par7);
            this.rightfrontleg2.render(par7);
            this.rightfrontfoot.render(par7);
            this.rightfrontclaw1.render(par7);
            this.rightfrontclaw2.render(par7);
            this.rightfrontclaw3.render(par7);
            this.leftfrontleg1.render(par7);
            this.leftfrontleg2.render(par7);
            this.leftfrontfoot.render(par7);
            this.leftfrontclaw1.render(par7);
            this.leftfrontclaw2.render(par7);
            this.leftfrontclaw3.render(par7);
            this.rightbackleg1.render(par7);
            this.rightbackleg2.render(par7);
            this.rightbackleg3.render(par7);
            this.rightbackfoot.render(par7);
            this.rightbackclaw1.render(par7);
            this.rightbackclaw2.render(par7);
            this.rightbackclaw3.render(par7);
            this.leftbackleg1.render(par7);
            this.leftbackleg2.render(par7);
            this.leftbackleg3.render(par7);
            this.leftbackfoot.render(par7);
            this.leftbackclaw1.render(par7);
            this.leftbackclaw2.render(par7);
            this.leftbackclaw3.render(par7);
            this.tail1.render(par7);
            this.tail2.render(par7);
            this.tail3.render(par7);
            this.tail4.render(par7);
            this.tail5.render(par7);
            this.jaw.render(par7);
            this.nose.render(par7);
            this.tooth1.render(par7);
            this.tooth2.render(par7);
            this.tooth3.render(par7);
            this.tooth4.render(par7);
        }
        GL11.glPopMatrix();
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity) {
        super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
        EntityNimatin var5 = (EntityNimatin)par7Entity;
        if (!var5.isSitting()) {
            float moveTail = MathHelper.cos(par1 * 0.6662f);
            float idleTail = MathHelper.cos(par3 * 0.18f);
            float tail1Yaw = idleTail * 0.05f + moveTail * 0.1f * par2;
            float tail2Yaw = idleTail * 0.09f + moveTail * 0.3f * par2;
            float tail3Yaw = idleTail * 0.13f + moveTail * 0.5f * par2;
            float tail4Yaw = idleTail * 0.16f + moveTail * 0.6f * par2;
            float tail5Yaw = idleTail * 0.19f + moveTail * 0.7f * par2;
            this.head.rotateAngleY = par4 / 57.295776f;
            this.nose.rotateAngleX = this.head.rotateAngleX = par5 / 57.295776f;
            this.nose.rotateAngleY = this.head.rotateAngleY;
            this.tooth1.rotateAngleY = this.head.rotateAngleY;
            this.tooth2.rotateAngleY = this.head.rotateAngleY;
            this.tooth3.rotateAngleY = this.head.rotateAngleY;
            this.tooth4.rotateAngleY = this.head.rotateAngleY;
            this.tooth1.rotateAngleX = this.head.rotateAngleX;
            this.tooth2.rotateAngleX = this.head.rotateAngleX;
            this.jaw.rotateAngleY = this.head.rotateAngleY;
            this.jaw.rotateAngleX = MathHelper.clamp_float(this.head.rotateAngleX * 0.9f, -0.2f, 1.1f);
            this.tooth3.rotateAngleX = this.jaw.rotateAngleX;
            this.tooth4.rotateAngleX = this.jaw.rotateAngleX;
            this.tail1.rotateAngleY = tail1Yaw;
            this.tail2.rotateAngleY = tail2Yaw;
            this.tail3.rotateAngleY = tail3Yaw;
            this.tail4.rotateAngleY = tail4Yaw;
            this.tail5.rotateAngleY = tail5Yaw;
            this.rightfrontleg1.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 0.8f * par2;
            this.leftfrontleg1.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 0.8f * par2;
            this.rightfrontleg2.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 1.2f * par2;
            this.leftfrontleg2.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 1.2f * par2;
            this.leftbackleg1.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 0.8f * par2;
            this.rightbackleg1.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 0.8f * par2;
            this.leftbackleg2.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 1.0f * par2;
            this.rightbackleg2.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 1.0f * par2;
            this.leftbackleg3.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 1.4f * par2;
            this.rightbackleg3.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 1.4f * par2;
            this.rightfrontfoot.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 1.2f * par2;
            this.leftfrontfoot.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 1.2f * par2;
            this.leftbackfoot.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 1.4f * par2;
            this.rightbackfoot.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 1.4f * par2;
            this.rightfrontclaw1.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 1.2f * par2;
            this.leftfrontclaw1.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 1.2f * par2;
            this.rightfrontclaw2.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 1.2f * par2;
            this.leftfrontclaw2.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 1.2f * par2;
            this.rightfrontclaw3.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 1.2f * par2;
            this.leftfrontclaw3.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 1.2f * par2;
            this.leftbackclaw1.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 1.4f * par2;
            this.rightbackclaw1.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 1.4f * par2;
            this.leftbackclaw2.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 1.4f * par2;
            this.rightbackclaw2.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 1.4f * par2;
            this.leftbackclaw3.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 1.4f * par2;
            this.rightbackclaw3.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 1.4f * par2;
        }
    }

    public void setLivingAnimations(EntityLivingBase par1EntityLiving, float par2, float par3, float par4) {
        EntityNimatin var5 = (EntityNimatin)par1EntityLiving;
        if (var5.isSitting()) {
            this.body.rotateAngleX = -0.5f;
            this.body.rotationPointY = -5.0f;
            this.head.rotationPointY = -5.0f;
            this.head.rotationPointZ = -28.0f;
            this.nose.rotationPointY = -5.0f;
            this.nose.rotationPointZ = -29.0f;
            this.jaw.rotationPointY = -5.0f;
            this.jaw.rotationPointZ = -29.0f;
            this.tooth1.rotationPointY = 0.0f;
            this.tooth1.rotationPointZ = -28.0f;
            this.tooth2.rotationPointY = 0.0f;
            this.tooth2.rotationPointZ = -28.0f;
            this.tooth3.rotationPointY = -5.0f;
            this.tooth3.rotationPointZ = -29.0f;
            this.tooth4.rotationPointY = -5.0f;
            this.tooth4.rotationPointZ = -29.0f;
            this.rightfrontleg1.rotationPointY = 2.0f;
            this.rightfrontleg1.rotationPointZ = -21.0f;
            this.rightfrontleg2.rotationPointZ = -21.0f;
            this.rightfrontfoot.rotationPointZ = -21.0f;
            this.rightfrontclaw1.rotationPointZ = -20.0f;
            this.rightfrontclaw2.rotationPointZ = -20.0f;
            this.rightfrontclaw3.rotationPointZ = -20.0f;
            this.rightfrontleg1.rotateAngleX = 0.0f;
            this.rightfrontleg2.rotateAngleX = 0.0f;
            this.rightfrontfoot.rotateAngleX = 0.0f;
            this.rightfrontclaw1.rotateAngleX = 0.0f;
            this.rightfrontclaw2.rotateAngleX = 0.0f;
            this.rightfrontclaw3.rotateAngleX = 0.0f;
            this.leftfrontleg1.rotationPointY = 2.0f;
            this.leftfrontleg1.rotationPointZ = -21.0f;
            this.leftfrontleg2.rotationPointZ = -21.0f;
            this.leftfrontfoot.rotationPointZ = -23.0f;
            this.leftfrontclaw1.rotationPointZ = -20.0f;
            this.leftfrontclaw2.rotationPointZ = -20.0f;
            this.leftfrontclaw3.rotationPointZ = -20.0f;
            this.leftfrontleg1.rotateAngleX = 0.0f;
            this.leftfrontleg2.rotateAngleX = 0.0f;
            this.leftfrontfoot.rotateAngleX = 0.0f;
            this.leftfrontclaw1.rotateAngleX = 0.0f;
            this.leftfrontclaw2.rotateAngleX = 0.0f;
            this.leftfrontclaw3.rotateAngleX = 0.0f;
            this.rightbackleg1.rotateAngleX = -1.57f;
            this.rightbackleg2.rotateAngleX = -1.57f;
            this.rightbackleg3.rotateAngleX = -1.57f;
            this.rightbackleg1.rotationPointY = 18.0f;
            this.rightbackleg2.rotationPointY = 18.0f;
            this.rightbackleg2.rotationPointZ = 10.0f;
            this.rightbackleg3.rotationPointY = 18.0f;
            this.rightbackfoot.rotateAngleX = -1.57f;
            this.rightbackfoot.rotationPointY = 18.0f;
            this.rightbackclaw1.rotateAngleX = -1.57f;
            this.rightbackclaw2.rotateAngleX = -1.57f;
            this.rightbackclaw3.rotateAngleX = -1.57f;
            this.rightbackclaw1.rotationPointY = 18.0f;
            this.rightbackclaw2.rotationPointY = 18.0f;
            this.rightbackclaw3.rotationPointY = 18.0f;
            this.leftbackleg1.rotateAngleX = -1.57f;
            this.leftbackleg2.rotateAngleX = -1.57f;
            this.leftbackleg3.rotateAngleX = -1.57f;
            this.leftbackleg1.rotationPointY = 18.0f;
            this.leftbackleg2.rotationPointY = 18.0f;
            this.leftbackleg2.rotationPointZ = 10.0f;
            this.leftbackleg3.rotationPointY = 18.0f;
            this.leftbackfoot.rotateAngleX = -1.57f;
            this.leftbackfoot.rotationPointY = 18.0f;
            this.leftbackclaw1.rotateAngleX = -1.57f;
            this.leftbackclaw2.rotateAngleX = -1.57f;
            this.leftbackclaw3.rotateAngleX = -1.57f;
            this.leftbackclaw1.rotationPointY = 18.0f;
            this.leftbackclaw2.rotationPointY = 18.0f;
            this.leftbackclaw3.rotationPointY = 18.0f;
            this.tail1.setRotationPoint(-1.0f, 21.0f, 14.0f);
            this.setRotation(this.tail1, 0.0f, 0.0f, 0.0f);
            this.tail2.setRotationPoint(-1.0f, 23.0f, 13.0f);
            this.setRotation(this.tail2, 0.2617994f, 0.0f, 0.0f);
            this.tail3.setRotationPoint(-1.0f, 20.0f, 14.0f);
            this.setRotation(this.tail3, 0.6981317f, 0.0f, 0.0f);
            this.tail4.setRotationPoint(-1.0f, 20.0f, 14.0f);
            this.setRotation(this.tail4, 0.6981317f, 0.0f, 0.0f);
            this.tail5.setRotationPoint(-1.0f, 33.0f, 22.0f);
            this.setRotation(this.tail5, 1.22173f, 0.0f, 0.0f);
        } else {
            this.head.setRotationPoint(-1.0f, 0.0f, -24.0f);
            this.setRotation(this.head, 0.0f, 0.0f, 0.0f);
            this.jaw.setRotationPoint(-1.0f, 0.0f, -24.0f);
            this.setRotation(this.jaw, 0.0f, 0.0f, 0.0f);
            this.nose.setRotationPoint(-1.0f, 0.0f, -24.0f);
            this.setRotation(this.nose, 0.0f, 0.0f, 0.0f);
            this.tooth1.setRotationPoint(-1.0f, 5.0f, -24.0f);
            this.setRotation(this.tooth1, 0.0f, 0.0f, 0.0f);
            this.tooth2.setRotationPoint(-1.0f, 5.0f, -24.0f);
            this.setRotation(this.tooth2, 0.0f, 0.0f, 0.0f);
            this.tooth3.setRotationPoint(-1.0f, 0.0f, -24.0f);
            this.setRotation(this.tooth3, 0.0f, 0.0f, 0.0f);
            this.tooth4.setRotationPoint(-1.0f, 0.0f, -24.0f);
            this.setRotation(this.tooth4, 0.0f, 0.0f, 0.0f);
            this.body.rotateAngleX = 0.0f;
            this.body.rotationPointY = -1.0f;
            this.rightfrontleg1.setRotationPoint(-9.0f, -1.0f, -12.0f);
            this.setRotation(this.rightfrontleg1, 0.0f, 0.0f, 0.0f);
            this.rightfrontleg2.setRotationPoint(-9.0f, -1.0f, -12.0f);
            this.setRotation(this.rightfrontleg2, 0.0f, 0.0f, 0.0f);
            this.rightfrontfoot.setRotationPoint(-9.0f, 0.0f, -12.0f);
            this.setRotation(this.rightfrontfoot, 0.0f, 0.0f, 0.0f);
            this.rightfrontclaw1.setRotationPoint(-9.0f, -1.0f, -12.0f);
            this.setRotation(this.rightfrontclaw1, 0.0f, 0.0f, 0.0f);
            this.rightfrontclaw2.setRotationPoint(-9.0f, -1.0f, -12.0f);
            this.setRotation(this.rightfrontclaw2, 0.0f, 0.0f, 0.0f);
            this.rightfrontclaw3.setRotationPoint(-9.0f, -1.0f, -12.0f);
            this.setRotation(this.rightfrontclaw3, 0.0f, 0.0f, 0.0f);
            this.leftfrontleg1.setRotationPoint(7.0f, -1.0f, -12.0f);
            this.setRotation(this.leftfrontleg1, 0.0f, 0.0f, 0.0f);
            this.leftfrontleg2.setRotationPoint(7.0f, -1.0f, -12.0f);
            this.setRotation(this.leftfrontleg2, 0.0f, 0.0f, 0.0f);
            this.leftfrontfoot.setRotationPoint(7.0f, 0.0f, -14.0f);
            this.setRotation(this.leftfrontfoot, 0.0f, 0.0f, 0.0f);
            this.leftfrontclaw1.setRotationPoint(7.0f, -1.0f, -12.0f);
            this.setRotation(this.leftfrontclaw1, 0.0f, 0.0f, 0.0f);
            this.leftfrontclaw2.setRotationPoint(7.0f, -1.0f, -12.0f);
            this.setRotation(this.leftfrontclaw2, 0.0f, 0.0f, 0.0f);
            this.leftfrontclaw3.setRotationPoint(7.0f, -1.0f, -12.0f);
            this.setRotation(this.leftfrontclaw3, 0.0f, 0.0f, 0.0f);
            this.rightbackleg1.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.setRotation(this.rightbackleg1, 0.0f, 0.0f, 0.0f);
            this.rightbackleg2.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.setRotation(this.rightbackleg2, 0.0f, 0.0f, 0.0f);
            this.rightbackleg3.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.setRotation(this.rightbackleg3, 0.0f, 0.0f, 0.0f);
            this.rightbackfoot.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.setRotation(this.rightbackfoot, 0.0f, 0.0f, 0.0f);
            this.rightbackclaw1.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.setRotation(this.rightbackclaw1, 0.0f, 0.0f, 0.0f);
            this.rightbackclaw2.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.setRotation(this.rightbackclaw2, 0.0f, 0.0f, 0.0f);
            this.rightbackclaw3.setRotationPoint(-9.0f, -1.0f, 12.0f);
            this.setRotation(this.rightbackclaw3, 0.0f, 0.0f, 0.0f);
            this.leftbackleg1.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.setRotation(this.leftbackleg1, 0.0f, 0.0f, 0.0f);
            this.leftbackleg2.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.setRotation(this.leftbackleg2, 0.0f, 0.0f, 0.0f);
            this.leftbackleg3.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.setRotation(this.leftbackleg3, 0.0f, 0.0f, 0.0f);
            this.leftbackfoot.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.setRotation(this.leftbackfoot, 0.0f, 0.0f, 0.0f);
            this.leftbackclaw1.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.setRotation(this.leftbackclaw1, 0.0f, 0.0f, 0.0f);
            this.leftbackclaw2.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.setRotation(this.leftbackclaw2, 0.0f, 0.0f, 0.0f);
            this.leftbackclaw3.setRotationPoint(7.0f, -1.0f, 12.0f);
            this.setRotation(this.leftbackclaw3, 0.0f, 0.0f, 0.0f);
            this.tail1.setRotationPoint(-1.0f, 0.0f, 21.0f);
            this.setRotation(this.tail1, -0.4363323f, 0.0f, 0.0f);
            this.tail2.setRotationPoint(-1.0f, 0.0f, 21.0f);
            this.setRotation(this.tail2, -0.4363323f, 0.0f, 0.0f);
            this.tail3.setRotationPoint(-1.0f, 0.0f, 21.0f);
            this.setRotation(this.tail3, 0.0872665f, 0.0f, 0.0f);
            this.tail4.setRotationPoint(-1.0f, 0.0f, 21.0f);
            this.setRotation(this.tail4, 0.0872665f, 0.0f, 0.0f);
            this.tail5.setRotationPoint(-1.0f, 0.0f, 21.0f);
            this.setRotation(this.tail5, 0.0872665f, 0.0f, 0.0f);
        }
        this.head.rotateAngleZ = var5.getInterestedAngle(par4) + var5.getShakeAngle(par4, 0.0f);
        this.jaw.rotateAngleZ = var5.getInterestedAngle(par4) + var5.getShakeAngle(par4, 0.0f);
        this.nose.rotateAngleZ = var5.getInterestedAngle(par4) + var5.getShakeAngle(par4, 0.0f);
        this.tooth1.rotateAngleZ = var5.getInterestedAngle(par4) + var5.getShakeAngle(par4, 0.0f);
        this.tooth2.rotateAngleZ = var5.getInterestedAngle(par4) + var5.getShakeAngle(par4, 0.0f);
        this.tooth3.rotateAngleZ = var5.getInterestedAngle(par4) + var5.getShakeAngle(par4, 0.0f);
        this.tooth4.rotateAngleZ = var5.getInterestedAngle(par4) + var5.getShakeAngle(par4, 0.0f);
        this.body.rotateAngleZ = var5.getShakeAngle(par4, -0.16f);
        this.tail1.rotateAngleZ = var5.getShakeAngle(par4, -0.2f);
        this.tail2.rotateAngleZ = var5.getShakeAngle(par4, -0.2f);
        this.tail3.rotateAngleZ = var5.getShakeAngle(par4, -0.2f);
        this.tail4.rotateAngleZ = var5.getShakeAngle(par4, -0.2f);
        this.tail5.rotateAngleZ = var5.getShakeAngle(par4, -0.2f);
    }
}


