package com.voidsrift.riftflux.palaria.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.util.MathHelper;

public class ModelCowasaurus
extends ModelBase {
    ModelRenderer body;
    ModelRenderer rightfoot1;
    ModelRenderer rightfoot2;
    ModelRenderer rightfoot3;
    ModelRenderer rightfoot4;
    ModelRenderer righttwins;
    ModelRenderer rightquadriceps;
    ModelRenderer lefttwins;
    ModelRenderer leftquadriceps;
    ModelRenderer leftfoot1;
    ModelRenderer leftfoot2;
    ModelRenderer leftfoot3;
    ModelRenderer leftfoot4;
    ModelRenderer bodyneck;
    ModelRenderer neck;
    ModelRenderer tit1;
    ModelRenderer tit2;
    ModelRenderer tit3;
    ModelRenderer tit4;
    ModelRenderer tit5;
    ModelRenderer head;
    ModelRenderer jaw;
    ModelRenderer tooth1;
    ModelRenderer tooth2;
    ModelRenderer tooth3;
    ModelRenderer tooth4;
    ModelRenderer tooth5;
    ModelRenderer tooth6;
    ModelRenderer tooth7;
    ModelRenderer tooth8;
    ModelRenderer tooth9;
    ModelRenderer tooth10;
    ModelRenderer tooth11;
    ModelRenderer tooth12;
    ModelRenderer tooth13;
    ModelRenderer tooth14;
    ModelRenderer tooth15;
    ModelRenderer tooth16;
    ModelRenderer tooth17;
    ModelRenderer tooth18;
    ModelRenderer tooth19;
    ModelRenderer tooth20;
    ModelRenderer horn1;
    ModelRenderer horn2;
    ModelRenderer tail1;
    ModelRenderer tail2;
    ModelRenderer tail3;
    ModelRenderer tail4;
    ModelRenderer leftarm;
    ModelRenderer rightarm;
    ModelRenderer lefthand1;
    ModelRenderer lefthand2;
    ModelRenderer lefthand3;
    ModelRenderer righthand1;
    ModelRenderer righthand2;
    ModelRenderer righthand3;
    ModelRenderer nose1;
    ModelRenderer nose2;
    ModelRenderer rightear1;
    ModelRenderer rightear2;
    ModelRenderer leftear1;
    ModelRenderer leftear2;

    public ModelCowasaurus() {
        this.textureWidth = 256;
        this.textureHeight = 256;
        this.body = new ModelRenderer(this, 100, 100);
        this.body.addBox(-6.0f, -5.0f, -7.0f, 11, 14, 15);
        this.body.setRotationPoint(1.0f, -3.0f, 10.0f);
        this.body.setTextureSize(256, 256);
        this.body.mirror = true;
        this.setRotation(this.body, 0.0f, 0.0f, 0.0f);
        this.rightfoot1 = new ModelRenderer(this, 160, 140);
        this.rightfoot1.addBox(-7.0f, 14.0f, -7.0f, 5, 7, 1);
        this.rightfoot1.setRotationPoint(-5.0f, 3.0f, 9.0f);
        this.rightfoot1.setTextureSize(256, 256);
        this.rightfoot1.mirror = true;
        this.setRotation(this.rightfoot1, 0.0f, 0.0f, 0.0f);
        this.rightfoot2 = new ModelRenderer(this, 160, 120);
        this.rightfoot2.addBox(-2.0f, 15.0f, -7.0f, 1, 6, 6);
        this.rightfoot2.setRotationPoint(-5.0f, 3.0f, 9.0f);
        this.rightfoot2.setTextureSize(256, 256);
        this.rightfoot2.mirror = true;
        this.setRotation(this.rightfoot2, 0.0f, 0.0f, 0.0f);
        this.rightfoot3 = new ModelRenderer(this, 181, 121);
        this.rightfoot3.addBox(-7.0f, 15.0f, -6.0f, 1, 6, 5);
        this.rightfoot3.setRotationPoint(-5.0f, 3.0f, 9.0f);
        this.rightfoot3.setTextureSize(256, 256);
        this.rightfoot3.mirror = true;
        this.setRotation(this.rightfoot3, 0.0f, 0.0f, 0.0f);
        this.rightfoot4 = new ModelRenderer(this, 176, 140);
        this.rightfoot4.addBox(-7.0f, 14.0f, -7.0f, 6, 1, 6);
        this.rightfoot4.setRotationPoint(-5.0f, 3.0f, 9.0f);
        this.rightfoot4.setTextureSize(256, 256);
        this.rightfoot4.mirror = true;
        this.setRotation(this.rightfoot4, 0.0f, 0.0f, 0.0f);
        this.righttwins = new ModelRenderer(this, 160, 100);
        this.righttwins.addBox(-6.5f, 5.0f, -5.0f, 5, 9, 5);
        this.righttwins.setRotationPoint(-5.0f, 3.0f, 9.0f);
        this.righttwins.setTextureSize(256, 256);
        this.righttwins.mirror = true;
        this.setRotation(this.righttwins, 0.122173f, 0.0f, 0.0f);
        this.rightquadriceps = new ModelRenderer(this, 160, 70);
        this.rightquadriceps.addBox(-8.0f, -1.0f, -8.0f, 8, 7, 11);
        this.rightquadriceps.setRotationPoint(-5.0f, 3.0f, 9.0f);
        this.rightquadriceps.setTextureSize(256, 256);
        this.rightquadriceps.mirror = true;
        this.setRotation(this.rightquadriceps, 0.122173f, 0.0f, 0.0f);
        this.lefttwins = new ModelRenderer(this, 70, 100);
        this.lefttwins.addBox(1.5f, 6.0f, -5.0f, 5, 9, 5);
        this.lefttwins.setRotationPoint(6.0f, 3.0f, 9.0f);
        this.lefttwins.setTextureSize(256, 256);
        this.lefttwins.mirror = true;
        this.setRotation(this.lefttwins, 0.122173f, 0.0f, 0.0f);
        this.leftquadriceps = new ModelRenderer(this, 60, 70);
        this.leftquadriceps.addBox(0.0f, -1.0f, -8.0f, 8, 7, 11);
        this.leftquadriceps.setRotationPoint(6.0f, 3.0f, 9.0f);
        this.leftquadriceps.setTextureSize(256, 256);
        this.leftquadriceps.mirror = true;
        this.setRotation(this.leftquadriceps, 0.122173f, 0.0f, 0.0f);
        this.leftfoot1 = new ModelRenderer(this, 80, 140);
        this.leftfoot1.addBox(2.0f, 15.0f, -7.0f, 5, 6, 1);
        this.leftfoot1.setRotationPoint(6.0f, 3.0f, 9.0f);
        this.leftfoot1.setTextureSize(256, 256);
        this.leftfoot1.mirror = true;
        this.setRotation(this.leftfoot1, 0.0f, 0.0f, 0.0f);
        this.leftfoot2 = new ModelRenderer(this, 78, 120);
        this.leftfoot2.addBox(1.0f, 14.0f, -7.0f, 1, 7, 6);
        this.leftfoot2.setRotationPoint(6.0f, 3.0f, 9.0f);
        this.leftfoot2.setTextureSize(256, 256);
        this.leftfoot2.mirror = true;
        this.setRotation(this.leftfoot2, 0.0f, 0.0f, 0.0f);
        this.leftfoot3 = new ModelRenderer(this, 57, 120);
        this.leftfoot3.addBox(6.0f, 15.0f, -6.0f, 1, 6, 5);
        this.leftfoot3.setRotationPoint(6.0f, 3.0f, 9.0f);
        this.leftfoot3.setTextureSize(256, 256);
        this.leftfoot3.mirror = true;
        this.setRotation(this.leftfoot3, 0.0f, 0.0f, 0.0f);
        this.leftfoot4 = new ModelRenderer(this, 52, 141);
        this.leftfoot4.addBox(2.0f, 14.0f, -7.0f, 5, 1, 6);
        this.leftfoot4.setRotationPoint(6.0f, 3.0f, 9.0f);
        this.leftfoot4.setTextureSize(256, 256);
        this.leftfoot4.mirror = true;
        this.setRotation(this.leftfoot4, 0.0f, 0.0f, 0.0f);
        this.bodyneck = new ModelRenderer(this, 103, 70);
        this.bodyneck.addBox(-5.0f, -5.0f, -12.0f, 11, 10, 14);
        this.bodyneck.setRotationPoint(0.0f, -4.0f, 3.0f);
        this.bodyneck.setTextureSize(256, 256);
        this.bodyneck.mirror = true;
        this.setRotation(this.bodyneck, 0.0f, 0.0f, 0.0f);
        this.neck = new ModelRenderer(this, 110, 53);
        this.neck.addBox(-4.0f, -3.7f, -6.0f, 9, 8, 6);
        this.neck.setRotationPoint(0.0f, -5.0f, -9.0f);
        this.neck.setTextureSize(256, 256);
        this.neck.mirror = true;
        this.setRotation(this.neck, 0.0f, 0.0f, 0.0f);
        this.tit1 = new ModelRenderer(this, 110, 136);
        this.tit1.addBox(0.0f, 0.0f, 0.0f, 7, 2, 8);
        this.tit1.setRotationPoint(-3.0f, 6.0f, 8.0f);
        this.tit1.setTextureSize(256, 256);
        this.tit1.mirror = true;
        this.setRotation(this.tit1, 0.0f, 0.0f, 0.0f);
        this.tit2 = new ModelRenderer(this, 110, 150);
        this.tit2.addBox(0.0f, 0.0f, 0.0f, 2, 2, 2);
        this.tit2.setRotationPoint(1.5f, 8.0f, 9.0f);
        this.tit2.setTextureSize(256, 256);
        this.tit2.mirror = true;
        this.setRotation(this.tit2, 0.0f, 0.0f, 0.0f);
        this.tit3 = new ModelRenderer(this, 130, 150);
        this.tit3.addBox(0.0f, 0.0f, 0.0f, 2, 2, 2);
        this.tit3.setRotationPoint(-2.5f, 8.0f, 9.0f);
        this.tit3.setTextureSize(256, 256);
        this.tit3.mirror = true;
        this.setRotation(this.tit3, 0.0f, 0.0f, 0.0f);
        this.tit4 = new ModelRenderer(this, 130, 160);
        this.tit4.addBox(0.0f, 0.0f, 0.0f, 2, 2, 2);
        this.tit4.setRotationPoint(1.5f, 8.0f, 13.0f);
        this.tit4.setTextureSize(256, 256);
        this.tit4.mirror = true;
        this.setRotation(this.tit4, 0.0f, 0.0f, 0.0f);
        this.tit5 = new ModelRenderer(this, 110, 160);
        this.tit5.addBox(0.0f, 0.0f, 0.0f, 2, 2, 2);
        this.tit5.setRotationPoint(-2.5f, 8.0f, 13.0f);
        this.tit5.setTextureSize(256, 256);
        this.tit5.mirror = true;
        this.setRotation(this.tit5, 0.0f, 0.0f, 0.0f);
        this.head = new ModelRenderer(this, 103, 25);
        this.head.addBox(-5.0f, -6.0f, -16.0f, 11, 10, 16);
        this.head.setRotationPoint(0.0f, -6.0f, -15.0f);
        this.head.setTextureSize(256, 256);
        this.head.mirror = true;
        this.setRotation(this.head, 0.0f, 0.0f, 0.0f);
        this.jaw = new ModelRenderer(this, 106, 5);
        this.jaw.addBox(-4.0f, 0.0f, -14.0f, 9, 3, 14);
        this.jaw.setRotationPoint(0.0f, -2.0f, -15.0f);
        this.jaw.setTextureSize(256, 256);
        this.jaw.mirror = true;
        this.setRotation(this.jaw, 0.0f, 0.0f, 0.0f);
        this.tooth1 = new ModelRenderer(this, 10, 200);
        this.tooth1.addBox(1.5f, 4.0f, -15.8f, 2, 2, 1);
        this.tooth1.setRotationPoint(0.0f, -6.0f, -15.0f);
        this.tooth1.setTextureSize(256, 256);
        this.tooth1.mirror = true;
        this.setRotation(this.tooth1, 0.0f, 0.0f, 0.0f);
        this.tooth2 = new ModelRenderer(this, 10, 200);
        this.tooth2.addBox(-2.5f, 4.0f, -15.8f, 2, 2, 1);
        this.tooth2.setRotationPoint(0.0f, -6.0f, -15.0f);
        this.tooth2.setTextureSize(256, 256);
        this.tooth2.mirror = true;
        this.setRotation(this.tooth2, 0.0f, 0.0f, 0.0f);
        this.tooth3 = new ModelRenderer(this, 10, 200);
        this.tooth3.addBox(-4.8f, 4.0f, -15.0f, 1, 2, 2);
        this.tooth3.setRotationPoint(0.0f, -6.0f, -15.0f);
        this.tooth3.setTextureSize(256, 256);
        this.tooth3.mirror = true;
        this.setRotation(this.tooth3, 0.0f, 0.0f, 0.0f);
        this.tooth4 = new ModelRenderer(this, 10, 200);
        this.tooth4.addBox(-4.8f, 4.0f, -11.0f, 1, 2, 1);
        this.tooth4.setRotationPoint(0.0f, -6.0f, -15.0f);
        this.tooth4.setTextureSize(256, 256);
        this.tooth4.mirror = true;
        this.setRotation(this.tooth4, 0.0f, 0.0f, 0.0f);
        this.tooth5 = new ModelRenderer(this, 10, 200);
        this.tooth5.addBox(-4.8f, 3.5f, -8.0f, 1, 2, 1);
        this.tooth5.setRotationPoint(0.0f, -6.0f, -15.0f);
        this.tooth5.setTextureSize(256, 256);
        this.tooth5.mirror = true;
        this.setRotation(this.tooth5, 0.0f, 0.0f, 0.0f);
        this.tooth6 = new ModelRenderer(this, 10, 200);
        this.tooth6.addBox(-4.8f, 4.0f, -5.0f, 1, 1, 1);
        this.tooth6.setRotationPoint(0.0f, -6.0f, -15.0f);
        this.tooth6.setTextureSize(256, 256);
        this.tooth6.mirror = true;
        this.setRotation(this.tooth6, 0.0f, 0.0f, 0.0f);
        this.tooth7 = new ModelRenderer(this, 10, 200);
        this.tooth7.addBox(4.8f, 4.0f, -15.0f, 1, 2, 2);
        this.tooth7.setRotationPoint(0.0f, -6.0f, -15.0f);
        this.tooth7.setTextureSize(256, 256);
        this.tooth7.mirror = true;
        this.setRotation(this.tooth7, 0.0f, 0.0f, 0.0f);
        this.tooth8 = new ModelRenderer(this, 10, 200);
        this.tooth8.addBox(4.8f, 4.0f, -11.0f, 1, 2, 1);
        this.tooth8.setRotationPoint(0.0f, -6.0f, -15.0f);
        this.tooth8.setTextureSize(256, 256);
        this.tooth8.mirror = true;
        this.setRotation(this.tooth8, 0.0f, 0.0f, 0.0f);
        this.tooth9 = new ModelRenderer(this, 10, 200);
        this.tooth9.addBox(4.8f, 3.5f, -8.0f, 1, 2, 1);
        this.tooth9.setRotationPoint(0.0f, -6.0f, -15.0f);
        this.tooth9.setTextureSize(256, 256);
        this.tooth9.mirror = true;
        this.setRotation(this.tooth9, 0.0f, 0.0f, 0.0f);
        this.tooth10 = new ModelRenderer(this, 10, 200);
        this.tooth10.addBox(4.8f, 4.0f, -5.0f, 1, 1, 1);
        this.tooth10.setRotationPoint(0.0f, -6.0f, -15.0f);
        this.tooth10.setTextureSize(256, 256);
        this.tooth10.mirror = true;
        this.setRotation(this.tooth10, 0.0f, 0.0f, 0.0f);
        this.tooth11 = new ModelRenderer(this, 10, 200);
        this.tooth11.addBox(-2.0f, -1.5f, -13.0f, 2, 2, 1);
        this.tooth11.setRotationPoint(0.0f, -2.0f, -15.0f);
        this.tooth11.setTextureSize(256, 256);
        this.tooth11.mirror = true;
        this.setRotation(this.tooth11, 0.0f, 0.0f, 0.0f);
        this.tooth12 = new ModelRenderer(this, 10, 200);
        this.tooth12.addBox(1.0f, -1.5f, -13.0f, 2, 2, 1);
        this.tooth12.setRotationPoint(0.0f, -2.0f, -15.0f);
        this.tooth12.setTextureSize(256, 256);
        this.tooth12.mirror = true;
        this.setRotation(this.tooth12, 0.0f, 0.0f, 0.0f);
        this.tooth13 = new ModelRenderer(this, 10, 200);
        this.tooth13.addBox(3.0f, -1.5f, -11.0f, 1, 2, 2);
        this.tooth13.setRotationPoint(0.0f, -2.0f, -15.0f);
        this.tooth13.setTextureSize(256, 256);
        this.tooth13.mirror = true;
        this.setRotation(this.tooth13, 0.0f, 0.0f, 0.0f);
        this.tooth14 = new ModelRenderer(this, 10, 200);
        this.tooth14.addBox(-3.0f, -1.5f, -11.0f, 1, 2, 2);
        this.tooth14.setRotationPoint(0.0f, -2.0f, -15.0f);
        this.tooth14.setTextureSize(256, 256);
        this.tooth14.mirror = true;
        this.setRotation(this.tooth14, 0.0f, 0.0f, 0.0f);
        this.tooth15 = new ModelRenderer(this, 10, 200);
        this.tooth15.addBox(3.0f, -1.5f, -8.0f, 1, 2, 1);
        this.tooth15.setRotationPoint(0.0f, -2.0f, -15.0f);
        this.tooth15.setTextureSize(256, 256);
        this.tooth15.mirror = true;
        this.setRotation(this.tooth15, 0.0f, 0.0f, 0.0f);
        this.tooth16 = new ModelRenderer(this, 10, 200);
        this.tooth16.addBox(-3.0f, -1.5f, -8.0f, 1, 2, 1);
        this.tooth16.setRotationPoint(0.0f, -2.0f, -15.0f);
        this.tooth16.setTextureSize(256, 256);
        this.tooth16.mirror = true;
        this.setRotation(this.tooth16, 0.0f, 0.0f, 0.0f);
        this.tooth17 = new ModelRenderer(this, 10, 200);
        this.tooth17.addBox(-3.0f, -1.0f, -6.0f, 1, 1, 1);
        this.tooth17.setRotationPoint(0.0f, -2.0f, -15.0f);
        this.tooth17.setTextureSize(256, 256);
        this.tooth17.mirror = true;
        this.setRotation(this.tooth17, 0.0f, 0.0f, 0.0f);
        this.tooth18 = new ModelRenderer(this, 10, 200);
        this.tooth18.addBox(3.0f, -1.0f, -6.0f, 1, 1, 1);
        this.tooth18.setRotationPoint(0.0f, -2.0f, -15.0f);
        this.tooth18.setTextureSize(256, 256);
        this.tooth18.mirror = true;
        this.setRotation(this.tooth18, 0.0f, 0.0f, 0.0f);
        this.tooth19 = new ModelRenderer(this, 10, 200);
        this.tooth19.addBox(-3.0f, -0.9f, -4.0f, 1, 1, 1);
        this.tooth19.setRotationPoint(0.0f, -2.0f, -15.0f);
        this.tooth19.setTextureSize(256, 256);
        this.tooth19.mirror = true;
        this.setRotation(this.tooth19, 0.0f, 0.0f, 0.0f);
        this.tooth20 = new ModelRenderer(this, 10, 200);
        this.tooth20.addBox(3.0f, -0.9f, -4.0f, 1, 1, 1);
        this.tooth20.setRotationPoint(0.0f, -2.0f, -15.0f);
        this.tooth20.setTextureSize(256, 256);
        this.tooth20.mirror = true;
        this.setRotation(this.tooth20, 0.0f, 0.0f, 0.0f);
        this.horn1 = new ModelRenderer(this, 90, 5);
        this.horn1.addBox(6.0f, -10.0f, -1.0f, 2, 6, 2);
        this.horn1.setRotationPoint(0.0f, -6.0f, -15.0f);
        this.horn1.setTextureSize(256, 256);
        this.horn1.mirror = true;
        this.setRotation(this.horn1, 0.0f, 0.0f, 0.0f);
        this.horn2 = new ModelRenderer(this, 155, 5);
        this.horn2.addBox(-7.0f, -10.0f, -1.0f, 2, 6, 2);
        this.horn2.setRotationPoint(0.0f, -6.0f, -15.0f);
        this.horn2.setTextureSize(256, 256);
        this.horn2.mirror = true;
        this.setRotation(this.horn2, 0.0f, 0.0f, 0.0f);
        this.tail1 = new ModelRenderer(this, 105, 170);
        this.tail1.addBox(-4.0f, -4.0f, 0.0f, 9, 10, 13);
        this.tail1.setRotationPoint(0.5f, -3.5f, 18.0f);
        this.tail1.setTextureSize(256, 256);
        this.tail1.mirror = true;
        this.setRotation(this.tail1, 0.0f, 0.0f, 0.0f);
        this.tail2 = new ModelRenderer(this, 109, 200);
        this.tail2.addBox(-4.0f, -3.5f, 13.0f, 8, 8, 10);
        this.tail2.setRotationPoint(0.5f, -3.5f, 18.0f);
        this.tail2.setTextureSize(256, 256);
        this.tail2.mirror = true;
        this.setRotation(this.tail2, 0.0f, 0.0f, 0.0f);
        this.tail3 = new ModelRenderer(this, 110, 222);
        this.tail3.addBox(-3.0f, -3.0f, 23.0f, 6, 6, 11);
        this.tail3.setRotationPoint(0.5f, -3.5f, 18.0f);
        this.tail3.setTextureSize(256, 256);
        this.tail3.mirror = true;
        this.setRotation(this.tail3, 0.0f, 0.0f, 0.0f);
        this.tail4 = new ModelRenderer(this, 115, 241);
        this.tail4.addBox(-2.0f, -2.5f, 34.0f, 4, 4, 8);
        this.tail4.setRotationPoint(0.5f, -3.5f, 18.0f);
        this.tail4.setTextureSize(256, 256);
        this.tail4.mirror = true;
        this.setRotation(this.tail4, 0.0f, 0.0f, 0.0f);
        this.leftarm = new ModelRenderer(this, 40, 70);
        this.leftarm.addBox(0.0f, 0.0f, -1.0f, 3, 7, 3);
        this.leftarm.setRotationPoint(6.0f, -3.0f, -5.0f);
        this.leftarm.setTextureSize(256, 256);
        this.leftarm.mirror = true;
        this.setRotation(this.leftarm, 0.0f, 0.0f, 0.0f);
        this.rightarm = new ModelRenderer(this, 205, 70);
        this.rightarm.addBox(-3.0f, 0.0f, -1.0f, 3, 7, 3);
        this.rightarm.setRotationPoint(-5.0f, -3.0f, -5.0f);
        this.rightarm.setTextureSize(256, 256);
        this.rightarm.mirror = true;
        this.setRotation(this.rightarm, 0.0f, 0.0f, 0.0f);
        this.lefthand1 = new ModelRenderer(this, 40, 82);
        this.lefthand1.addBox(0.0f, 7.0f, -1.0f, 3, 2, 1);
        this.lefthand1.setRotationPoint(6.0f, -3.0f, -5.0f);
        this.lefthand1.setTextureSize(256, 256);
        this.lefthand1.mirror = true;
        this.setRotation(this.lefthand1, 0.0f, 0.0f, 0.0f);
        this.lefthand2 = new ModelRenderer(this, 40, 88);
        this.lefthand2.addBox(0.0f, 7.0f, 0.0f, 1, 2, 2);
        this.lefthand2.setRotationPoint(6.0f, -3.0f, -5.0f);
        this.lefthand2.setTextureSize(256, 256);
        this.lefthand2.mirror = true;
        this.setRotation(this.lefthand2, 0.0f, 0.0f, 0.0f);
        this.lefthand3 = new ModelRenderer(this, 40, 94);
        this.lefthand3.addBox(2.0f, 7.0f, 0.0f, 1, 2, 2);
        this.lefthand3.setRotationPoint(6.0f, -3.0f, -5.0f);
        this.lefthand3.setTextureSize(256, 256);
        this.lefthand3.mirror = true;
        this.setRotation(this.lefthand3, 0.0f, 0.0f, 0.0f);
        this.righthand1 = new ModelRenderer(this, 211, 88);
        this.righthand1.addBox(-1.0f, 7.0f, 0.0f, 1, 2, 2);
        this.righthand1.setRotationPoint(-5.0f, -3.0f, -5.0f);
        this.righthand1.setTextureSize(256, 256);
        this.righthand1.mirror = true;
        this.setRotation(this.righthand1, 0.0f, 0.0f, 0.0f);
        this.righthand2 = new ModelRenderer(this, 209, 82);
        this.righthand2.addBox(-3.0f, 7.0f, -1.0f, 3, 2, 1);
        this.righthand2.setRotationPoint(-5.0f, -3.0f, -5.0f);
        this.righthand2.setTextureSize(256, 256);
        this.righthand2.mirror = true;
        this.setRotation(this.righthand2, 0.0f, 0.0f, 0.0f);
        this.righthand3 = new ModelRenderer(this, 211, 93);
        this.righthand3.addBox(-3.0f, 7.0f, 0.0f, 1, 2, 2);
        this.righthand3.setRotationPoint(-5.0f, -3.0f, -5.0f);
        this.righthand3.setTextureSize(256, 256);
        this.righthand3.mirror = true;
        this.setRotation(this.righthand3, 0.0f, 0.0f, 0.0f);
        this.nose1 = new ModelRenderer(this, 15, 20);
        this.nose1.addBox(-5.0f, 0.0f, -17.0f, 11, 4, 1);
        this.nose1.setRotationPoint(0.0f, -6.0f, -15.0f);
        this.nose1.setTextureSize(256, 256);
        this.nose1.mirror = true;
        this.setRotation(this.nose1, 0.0f, 0.0f, 0.0f);
        this.nose2 = new ModelRenderer(this, 19, 15);
        this.nose2.addBox(-3.0f, -2.0f, -17.0f, 7, 2, 1);
        this.nose2.setRotationPoint(0.0f, -6.0f, -15.0f);
        this.nose2.setTextureSize(256, 256);
        this.nose2.mirror = true;
        this.setRotation(this.nose2, 0.0f, 0.0f, 0.0f);
        this.rightear1 = new ModelRenderer(this, 20, 5);
        this.rightear1.addBox(5.5f, -3.0f, -1.0f, 1, 3, 3);
        this.rightear1.setRotationPoint(0.0f, -6.0f, -15.0f);
        this.rightear1.setTextureSize(256, 256);
        this.rightear1.mirror = true;
        this.setRotation(this.rightear1, 0.0f, 0.4363323f, -0.0872665f);
        this.rightear2 = new ModelRenderer(this, 30, 5);
        this.rightear2.addBox(5.5f, -3.0f, 2.0f, 1, 2, 1);
        this.rightear2.setRotationPoint(0.0f, -6.0f, -15.0f);
        this.rightear2.setTextureSize(256, 256);
        this.rightear2.mirror = true;
        this.setRotation(this.rightear2, 0.0f, 0.4363323f, -0.0872665f);
        this.leftear1 = new ModelRenderer(this, 12, 5);
        this.leftear1.addBox(-5.5f, -3.0f, -1.0f, 1, 3, 3);
        this.leftear1.setRotationPoint(0.0f, -6.0f, -15.0f);
        this.leftear1.setTextureSize(256, 256);
        this.leftear1.mirror = true;
        this.setRotation(this.leftear1, 0.0f, -0.4363323f, 0.0872665f);
        this.leftear2 = new ModelRenderer(this, 30, 5);
        this.leftear2.addBox(-5.5f, -3.0f, 2.0f, 1, 2, 1);
        this.leftear2.setRotationPoint(0.0f, -6.0f, -15.0f);
        this.leftear2.setTextureSize(256, 256);
        this.leftear2.mirror = true;
        this.setRotation(this.leftear2, 0.0f, -0.4363323f, 0.0872665f);
    }

    public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7) {
        super.render(par1Entity, par2, par3, par4, par5, par6, par7);
        this.setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
        this.body.render(par7);
        this.rightfoot1.render(par7);
        this.rightfoot2.render(par7);
        this.rightfoot3.render(par7);
        this.rightfoot4.render(par7);
        this.righttwins.render(par7);
        this.rightquadriceps.render(par7);
        this.lefttwins.render(par7);
        this.leftquadriceps.render(par7);
        this.leftfoot1.render(par7);
        this.leftfoot2.render(par7);
        this.leftfoot3.render(par7);
        this.leftfoot4.render(par7);
        this.bodyneck.render(par7);
        this.neck.render(par7);
        this.tit1.render(par7);
        this.tit2.render(par7);
        this.tit3.render(par7);
        this.tit4.render(par7);
        this.tit5.render(par7);
        this.head.render(par7);
        this.jaw.render(par7);
        this.tooth1.render(par7);
        this.tooth2.render(par7);
        this.tooth3.render(par7);
        this.tooth4.render(par7);
        this.tooth5.render(par7);
        this.tooth6.render(par7);
        this.tooth7.render(par7);
        this.tooth8.render(par7);
        this.tooth9.render(par7);
        this.tooth10.render(par7);
        this.tooth11.render(par7);
        this.tooth12.render(par7);
        this.tooth13.render(par7);
        this.tooth14.render(par7);
        this.tooth15.render(par7);
        this.tooth16.render(par7);
        this.tooth17.render(par7);
        this.tooth18.render(par7);
        this.tooth19.render(par7);
        this.tooth20.render(par7);
        this.horn1.render(par7);
        this.horn2.render(par7);
        this.tail1.render(par7);
        this.tail2.render(par7);
        this.tail3.render(par7);
        this.tail4.render(par7);
        this.leftarm.render(par7);
        this.rightarm.render(par7);
        this.lefthand1.render(par7);
        this.lefthand2.render(par7);
        this.lefthand3.render(par7);
        this.righthand1.render(par7);
        this.righthand2.render(par7);
        this.righthand3.render(par7);
        this.nose1.render(par7);
        this.nose2.render(par7);
        this.rightear1.render(par7);
        this.rightear2.render(par7);
        this.leftear1.render(par7);
        this.leftear2.render(par7);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity) {
        super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
        this.head.rotateAngleY = par4 / 57.295776f;
        this.head.rotateAngleX = par5 / 57.295776f;
        this.rightear1.rotateAngleY = this.head.rotateAngleY;
        this.rightear1.rotateAngleX = this.head.rotateAngleX;
        this.rightear2.rotateAngleY = this.head.rotateAngleY;
        this.rightear2.rotateAngleX = this.head.rotateAngleX;
        this.leftear1.rotateAngleY = this.head.rotateAngleY;
        this.leftear1.rotateAngleX = this.head.rotateAngleX;
        this.leftear2.rotateAngleY = this.head.rotateAngleY;
        this.leftear2.rotateAngleX = this.head.rotateAngleX;
        this.nose1.rotateAngleY = this.head.rotateAngleY;
        this.nose1.rotateAngleX = this.head.rotateAngleX;
        this.nose2.rotateAngleY = this.head.rotateAngleY;
        this.nose2.rotateAngleX = this.head.rotateAngleX;
        this.horn1.rotateAngleY = this.head.rotateAngleY;
        this.horn1.rotateAngleX = this.head.rotateAngleX;
        this.horn2.rotateAngleY = this.head.rotateAngleY;
        this.horn2.rotateAngleX = this.head.rotateAngleX;
        this.tooth1.rotateAngleY = this.head.rotateAngleY;
        this.tooth2.rotateAngleY = this.head.rotateAngleY;
        this.tooth3.rotateAngleY = this.head.rotateAngleY;
        this.tooth4.rotateAngleY = this.head.rotateAngleY;
        this.tooth5.rotateAngleY = this.head.rotateAngleY;
        this.tooth6.rotateAngleY = this.head.rotateAngleY;
        this.tooth7.rotateAngleY = this.head.rotateAngleY;
        this.tooth8.rotateAngleY = this.head.rotateAngleY;
        this.tooth9.rotateAngleY = this.head.rotateAngleY;
        this.tooth10.rotateAngleY = this.head.rotateAngleY;
        this.tooth1.rotateAngleX = this.head.rotateAngleX;
        this.tooth2.rotateAngleX = this.head.rotateAngleX;
        this.tooth3.rotateAngleX = this.head.rotateAngleX;
        this.tooth4.rotateAngleX = this.head.rotateAngleX;
        this.tooth5.rotateAngleX = this.head.rotateAngleX;
        this.tooth6.rotateAngleX = this.head.rotateAngleX;
        this.tooth7.rotateAngleX = this.head.rotateAngleX;
        this.tooth8.rotateAngleX = this.head.rotateAngleX;
        this.tooth9.rotateAngleX = this.head.rotateAngleX;
        this.tooth10.rotateAngleX = this.head.rotateAngleX;
        this.jaw.rotateAngleY = this.head.rotateAngleY;
        this.jaw.rotateAngleX = par5 / 25.46479f;
        this.tooth11.rotateAngleY = this.jaw.rotateAngleY;
        this.tooth12.rotateAngleY = this.jaw.rotateAngleY;
        this.tooth13.rotateAngleY = this.jaw.rotateAngleY;
        this.tooth14.rotateAngleY = this.jaw.rotateAngleY;
        this.tooth15.rotateAngleY = this.jaw.rotateAngleY;
        this.tooth16.rotateAngleY = this.jaw.rotateAngleY;
        this.tooth17.rotateAngleY = this.jaw.rotateAngleY;
        this.tooth18.rotateAngleY = this.jaw.rotateAngleY;
        this.tooth19.rotateAngleY = this.jaw.rotateAngleY;
        this.tooth20.rotateAngleY = this.jaw.rotateAngleY;
        this.tooth11.rotateAngleX = this.jaw.rotateAngleX;
        this.tooth12.rotateAngleX = this.jaw.rotateAngleX;
        this.tooth13.rotateAngleX = this.jaw.rotateAngleX;
        this.tooth14.rotateAngleX = this.jaw.rotateAngleX;
        this.tooth15.rotateAngleX = this.jaw.rotateAngleX;
        this.tooth16.rotateAngleX = this.jaw.rotateAngleX;
        this.tooth17.rotateAngleX = this.jaw.rotateAngleX;
        this.tooth18.rotateAngleX = this.jaw.rotateAngleX;
        this.tooth19.rotateAngleX = this.jaw.rotateAngleX;
        this.tooth20.rotateAngleX = this.jaw.rotateAngleX;
        this.rightquadriceps.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 0.5f * par2;
        this.leftquadriceps.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 0.5f * par2;
        this.righttwins.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 0.8f * par2;
        this.lefttwins.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 1.0f * par2;
        this.rightfoot1.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 1.0f * par2;
        this.leftfoot1.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 1.0f * par2;
        this.rightfoot2.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 1.0f * par2;
        this.leftfoot2.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 1.0f * par2;
        this.rightfoot3.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 1.0f * par2;
        this.leftfoot3.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 1.0f * par2;
        this.rightfoot4.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 1.0f * par2;
        this.leftfoot4.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 1.0f * par2;
        this.tail1.rotateAngleY = MathHelper.cos(par1 * 0.6662f) * 0.2f * par2;
        this.tail1.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 0.1f * par2;
        this.tail2.rotateAngleY = MathHelper.cos(par1 * 0.6662f) * 0.3f * par2;
        this.tail2.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 0.1f * par2;
        this.tail3.rotateAngleY = MathHelper.cos(par1 * 0.6662f) * 0.4f * par2;
        this.tail3.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 0.1f * par2;
        this.tail4.rotateAngleY = MathHelper.cos(par1 * 0.6662f) * 0.5f * par2;
        this.tail4.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 0.1f * par2;
        this.leftarm.rotateAngleY = this.rightquadriceps.rotateAngleX;
        this.rightarm.rotateAngleY = this.rightquadriceps.rotateAngleX;
        this.lefthand1.rotateAngleY = this.rightquadriceps.rotateAngleX;
        this.lefthand2.rotateAngleY = this.rightquadriceps.rotateAngleX;
        this.lefthand3.rotateAngleY = this.rightquadriceps.rotateAngleX;
        this.righthand1.rotateAngleY = this.rightquadriceps.rotateAngleX;
        this.righthand2.rotateAngleY = this.rightquadriceps.rotateAngleX;
        this.righthand3.rotateAngleY = this.rightquadriceps.rotateAngleX;
        this.leftarm.rotateAngleX = this.rightquadriceps.rotateAngleX;
        this.rightarm.rotateAngleX = this.rightquadriceps.rotateAngleX;
        this.lefthand1.rotateAngleX = this.rightquadriceps.rotateAngleX;
        this.lefthand2.rotateAngleX = this.rightquadriceps.rotateAngleX;
        this.lefthand3.rotateAngleX = this.rightquadriceps.rotateAngleX;
        this.righthand1.rotateAngleX = this.rightquadriceps.rotateAngleX;
        this.righthand2.rotateAngleX = this.rightquadriceps.rotateAngleX;
        this.righthand3.rotateAngleX = this.rightquadriceps.rotateAngleX;
        this.leftarm.rotateAngleZ = this.rightquadriceps.rotateAngleX;
        this.rightarm.rotateAngleZ = this.rightquadriceps.rotateAngleX;
        this.lefthand1.rotateAngleZ = this.rightquadriceps.rotateAngleX;
        this.lefthand2.rotateAngleZ = this.rightquadriceps.rotateAngleX;
        this.lefthand3.rotateAngleZ = this.rightquadriceps.rotateAngleX;
        this.righthand1.rotateAngleZ = this.rightquadriceps.rotateAngleX;
        this.righthand2.rotateAngleZ = this.rightquadriceps.rotateAngleX;
        this.righthand3.rotateAngleZ = this.rightquadriceps.rotateAngleX;
    }
}


