package com.voidsrift.riftflux.palaria.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.util.MathHelper;

public class ModelRaptorChicken
extends ModelBase {
    ModelRenderer body;
    ModelRenderer neck;
    ModelRenderer mouth;
    ModelRenderer mouth2;
    ModelRenderer cresta;
    ModelRenderer leftleg;
    ModelRenderer rightleg;
    ModelRenderer leftwing;
    ModelRenderer rightwing;
    ModelRenderer headhair1;
    ModelRenderer headhair2;
    ModelRenderer headhair3;
    ModelRenderer headhair4;
    ModelRenderer headhair5;
    ModelRenderer backhair1;
    ModelRenderer backhair2;
    ModelRenderer backhair3;
    ModelRenderer backhair4;
    ModelRenderer backhair5;
    ModelRenderer leftwing1;
    ModelRenderer leftwing2;
    ModelRenderer leftwing3;
    ModelRenderer leftwing4;
    ModelRenderer rightwing1;
    ModelRenderer rightwing2;
    ModelRenderer rightwing3;
    ModelRenderer rightwing4;
    ModelRenderer tooth1;
    ModelRenderer tooth2;
    ModelRenderer tooth3;
    ModelRenderer tooth4;

    public ModelRaptorChicken() {
        this.textureWidth = 128;
        this.textureHeight = 128;
        this.body = new ModelRenderer(this, 40, 33);
        this.body.addBox(-3.0f, -3.0f, -4.0f, 6, 6, 10);
        this.body.setRotationPoint(0.0f, 15.0f, 1.0f);
        this.body.setTextureSize(128, 128);
        this.body.mirror = true;
        this.setRotation(this.body, 0.0f, 0.0f, 0.0f);
        this.neck = new ModelRenderer(this, 49, 15);
        this.neck.addBox(-2.0f, -9.0f, -2.0f, 4, 9, 3);
        this.neck.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.neck.setTextureSize(128, 128);
        this.neck.mirror = true;
        this.setRotation(this.neck, 0.0f, 0.0f, 0.0f);
        this.mouth = new ModelRenderer(this, 65, 16);
        this.mouth.addBox(-2.0f, -7.0f, -4.0f, 4, 2, 2);
        this.mouth.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.mouth.setTextureSize(128, 128);
        this.mouth.mirror = true;
        this.setRotation(this.mouth, 0.0f, 0.0f, 0.0f);
        this.mouth2 = new ModelRenderer(this, 65, 16);
        this.mouth2.addBox(-2.0f, -7.0f, -4.0f, 4, 2, 2);
        this.mouth2.setRotationPoint(0.0f, 14.01f, -3.0f);
        this.mouth2.setTextureSize(128, 128);
        this.mouth2.mirror = true;
        this.setRotation(this.mouth2, 0.0f, 0.0f, 0.0f);
        this.cresta = new ModelRenderer(this, 65, 25);
        this.cresta.addBox(-1.0f, -5.0f, -3.0f, 2, 2, 2);
        this.cresta.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.cresta.setTextureSize(128, 128);
        this.cresta.mirror = true;
        this.setRotation(this.cresta, 0.0f, 0.0f, 0.0f);
        this.leftleg = new ModelRenderer(this, 60, 55);
        this.leftleg.addBox(-1.0f, 0.0f, -3.0f, 3, 6, 3);
        this.leftleg.setRotationPoint(1.0f, 18.0f, 4.0f);
        this.leftleg.setTextureSize(128, 128);
        this.leftleg.mirror = true;
        this.setRotation(this.leftleg, 0.0f, 0.0f, 0.0f);
        this.rightleg = new ModelRenderer(this, 40, 55);
        this.rightleg.addBox(-1.0f, 0.0f, -3.0f, 3, 6, 3);
        this.rightleg.setRotationPoint(-2.0f, 18.0f, 4.0f);
        this.rightleg.setTextureSize(128, 128);
        this.rightleg.mirror = true;
        this.setRotation(this.rightleg, 0.0f, 0.0f, 0.0f);
        this.leftwing = new ModelRenderer(this, 18, 34);
        this.leftwing.addBox(-1.0f, 0.0f, -4.0f, 1, 5, 8);
        this.leftwing.setRotationPoint(4.0f, 12.0f, 2.0f);
        this.leftwing.setTextureSize(128, 128);
        this.leftwing.mirror = true;
        this.setRotation(this.leftwing, 0.0f, 0.0f, 0.0f);
        this.rightwing = new ModelRenderer(this, 78, 34);
        this.rightwing.addBox(0.0f, 0.0f, -4.0f, 1, 5, 8);
        this.rightwing.setRotationPoint(-4.0f, 12.0f, 2.0f);
        this.rightwing.setTextureSize(128, 128);
        this.rightwing.mirror = true;
        this.setRotation(this.rightwing, 0.0f, 0.0f, 0.0f);
        this.headhair1 = new ModelRenderer(this, 60, 11);
        this.headhair1.addBox(-0.5f, -10.0f, -2.5f, 1, 2, 1);
        this.headhair1.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.headhair1.setTextureSize(128, 128);
        this.headhair1.mirror = true;
        this.setRotation(this.headhair1, 0.0f, 0.0f, 0.0f);
        this.headhair2 = new ModelRenderer(this, 55, 8);
        this.headhair2.addBox(-0.5f, -11.0f, -1.5f, 1, 1, 1);
        this.headhair2.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.headhair2.setTextureSize(128, 128);
        this.headhair2.mirror = true;
        this.setRotation(this.headhair2, 0.0f, 0.0f, 0.0f);
        this.headhair3 = new ModelRenderer(this, 47, 11);
        this.headhair3.addBox(-0.5f, -10.0f, 0.0f, 1, 2, 1);
        this.headhair3.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.headhair3.setTextureSize(128, 128);
        this.headhair3.mirror = true;
        this.setRotation(this.headhair3, 0.0f, 0.0f, 0.0f);
        this.headhair4 = new ModelRenderer(this, 42, 8);
        this.headhair4.addBox(-0.5f, -11.0f, 1.0f, 1, 1, 1);
        this.headhair4.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.headhair4.setTextureSize(128, 128);
        this.headhair4.mirror = true;
        this.setRotation(this.headhair4, 0.0f, 0.0f, 0.0f);
        this.headhair5 = new ModelRenderer(this, 43, 16);
        this.headhair5.addBox(-0.5f, -9.0f, 1.0f, 1, 1, 1);
        this.headhair5.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.headhair5.setTextureSize(128, 128);
        this.headhair5.mirror = true;
        this.setRotation(this.headhair5, 0.0f, 0.0f, 0.0f);
        this.backhair1 = new ModelRenderer(this, 48, 100);
        this.backhair1.addBox(0.0f, 0.0f, 0.0f, 1, 1, 3);
        this.backhair1.setRotationPoint(-0.5f, 11.0f, 4.0f);
        this.backhair1.setTextureSize(128, 128);
        this.backhair1.mirror = true;
        this.setRotation(this.backhair1, 0.0f, 0.0f, 0.0f);
        this.backhair2 = new ModelRenderer(this, 52, 95);
        this.backhair2.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1);
        this.backhair2.setRotationPoint(-0.5f, 10.0f, 4.0f);
        this.backhair2.setTextureSize(128, 128);
        this.backhair2.mirror = true;
        this.setRotation(this.backhair2, 0.0f, 0.0f, 0.0f);
        this.backhair3 = new ModelRenderer(this, 47, 92);
        this.backhair3.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1);
        this.backhair3.setRotationPoint(-0.5f, 9.0f, 5.0f);
        this.backhair3.setTextureSize(128, 128);
        this.backhair3.mirror = true;
        this.setRotation(this.backhair3, 0.0f, 0.0f, 0.0f);
        this.backhair4 = new ModelRenderer(this, 40, 97);
        this.backhair4.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1);
        this.backhair4.setRotationPoint(-0.4666667f, 10.0f, 7.0f);
        this.backhair4.setTextureSize(128, 128);
        this.backhair4.mirror = true;
        this.setRotation(this.backhair4, 0.0f, 0.0f, 0.0f);
        this.backhair5 = new ModelRenderer(this, 35, 94);
        this.backhair5.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1);
        this.backhair5.setRotationPoint(-0.4666667f, 9.0f, 8.0f);
        this.backhair5.setTextureSize(128, 128);
        this.backhair5.mirror = true;
        this.setRotation(this.backhair5, 0.0f, 0.0f, 0.0f);
        this.leftwing1 = new ModelRenderer(this, 18, 50);
        this.leftwing1.addBox(-1.0f, 5.0f, -4.0f, 1, 3, 4);
        this.leftwing1.setRotationPoint(4.0f, 12.0f, 2.0f);
        this.leftwing1.setTextureSize(128, 128);
        this.leftwing1.mirror = true;
        this.setRotation(this.leftwing1, 0.0f, 0.0f, 0.0f);
        this.leftwing2 = new ModelRenderer(this, 18, 60);
        this.leftwing2.addBox(-1.0f, 6.0f, -3.0f, 1, 3, 4);
        this.leftwing2.setRotationPoint(4.0f, 12.0f, 2.0f);
        this.leftwing2.setTextureSize(128, 128);
        this.leftwing2.mirror = true;
        this.setRotation(this.leftwing2, 0.0f, 0.0f, 0.0f);
        this.leftwing3 = new ModelRenderer(this, 21, 69);
        this.leftwing3.addBox(-1.0f, 7.0f, 1.0f, 1, 2, 1);
        this.leftwing3.setRotationPoint(4.0f, 12.0f, 2.0f);
        this.leftwing3.setTextureSize(128, 128);
        this.leftwing3.mirror = true;
        this.setRotation(this.leftwing3, 0.0f, 0.0f, 0.0f);
        this.leftwing4 = new ModelRenderer(this, 21, 74);
        this.leftwing4.addBox(-1.0f, 8.0f, 2.0f, 1, 1, 1);
        this.leftwing4.setRotationPoint(4.0f, 12.0f, 2.0f);
        this.leftwing4.setTextureSize(128, 128);
        this.leftwing4.mirror = true;
        this.setRotation(this.leftwing4, 0.0f, 0.0f, 0.0f);
        this.rightwing1 = new ModelRenderer(this, 86, 50);
        this.rightwing1.addBox(0.0f, 5.0f, -4.0f, 1, 3, 4);
        this.rightwing1.setRotationPoint(-4.0f, 11.86667f, 2.0f);
        this.rightwing1.setTextureSize(128, 128);
        this.rightwing1.mirror = true;
        this.setRotation(this.rightwing1, 0.0f, 0.0f, 0.0f);
        this.rightwing2 = new ModelRenderer(this, 86, 60);
        this.rightwing2.addBox(0.0f, 6.0f, -3.0f, 1, 3, 4);
        this.rightwing2.setRotationPoint(-4.0f, 12.0f, 2.0f);
        this.rightwing2.setTextureSize(128, 128);
        this.rightwing2.mirror = true;
        this.setRotation(this.rightwing2, 0.0f, 0.0f, 0.0f);
        this.rightwing3 = new ModelRenderer(this, 89, 69);
        this.rightwing3.addBox(0.0f, 7.0f, 1.0f, 1, 2, 1);
        this.rightwing3.setRotationPoint(-4.0f, 12.0f, 2.0f);
        this.rightwing3.setTextureSize(128, 128);
        this.rightwing3.mirror = true;
        this.setRotation(this.rightwing3, 0.0f, 0.0f, 0.0f);
        this.rightwing4 = new ModelRenderer(this, 89, 74);
        this.rightwing4.addBox(0.0f, 8.0f, 2.0f, 1, 1, 1);
        this.rightwing4.setRotationPoint(-4.0f, 12.0f, 2.0f);
        this.rightwing4.setTextureSize(128, 128);
        this.rightwing4.mirror = true;
        this.setRotation(this.rightwing4, 0.0f, 0.0f, 0.0f);
        this.tooth1 = new ModelRenderer(this, 59, 21);
        this.tooth1.addBox(0.4f, -6.0f, -4.1f, 1, 1, 1);
        this.tooth1.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.tooth1.setTextureSize(128, 128);
        this.tooth1.mirror = true;
        this.setRotation(this.tooth1, 0.0f, 0.0f, 0.0f);
        this.tooth2 = new ModelRenderer(this, 100, 25);
        this.tooth2.addBox(-2.1f, -6.0f, -3.9f, 1, 1, 1);
        this.tooth2.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.tooth2.setTextureSize(128, 128);
        this.tooth2.mirror = true;
        this.setRotation(this.tooth2, 0.0f, 0.0f, 0.0f);
        this.tooth3 = new ModelRenderer(this, 59, 24);
        this.tooth3.addBox(-1.4f, -6.0f, -4.1f, 1, 1, 1);
        this.tooth3.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.tooth3.setTextureSize(128, 128);
        this.tooth3.mirror = true;
        this.setRotation(this.tooth3, 0.0f, 0.0f, 0.0f);
        this.tooth4 = new ModelRenderer(this, 100, 20);
        this.tooth4.addBox(1.1f, -6.0f, -3.9f, 1, 1, 1);
        this.tooth4.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.tooth4.setTextureSize(128, 128);
        this.tooth4.mirror = true;
        this.setRotation(this.tooth4, 0.0f, 0.0f, 0.0f);
    }

    public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7) {
        super.render(par1Entity, par2, par3, par4, par5, par6, par7);
        this.setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
        this.body.render(par7);
        this.neck.render(par7);
        this.mouth.render(par7);
        this.mouth2.render(par7);
        this.cresta.render(par7);
        this.leftleg.render(par7);
        this.rightleg.render(par7);
        this.leftwing.render(par7);
        this.rightwing.render(par7);
        this.headhair1.render(par7);
        this.headhair2.render(par7);
        this.headhair3.render(par7);
        this.headhair4.render(par7);
        this.headhair5.render(par7);
        this.backhair1.render(par7);
        this.backhair2.render(par7);
        this.backhair3.render(par7);
        this.backhair4.render(par7);
        this.backhair5.render(par7);
        this.leftwing1.render(par7);
        this.leftwing2.render(par7);
        this.leftwing3.render(par7);
        this.leftwing4.render(par7);
        this.rightwing1.render(par7);
        this.rightwing2.render(par7);
        this.rightwing3.render(par7);
        this.rightwing4.render(par7);
        this.tooth1.render(par7);
        this.tooth2.render(par7);
        this.tooth3.render(par7);
        this.tooth4.render(par7);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity) {
        super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
        this.neck.rotateAngleX = par5 / 57.295776f;
        this.neck.rotateAngleY = par4 / 57.295776f;
        this.cresta.rotateAngleX = this.neck.rotateAngleX;
        this.cresta.rotateAngleY = this.neck.rotateAngleY;
        this.mouth.rotateAngleX = this.neck.rotateAngleX;
        this.mouth.rotateAngleY = this.neck.rotateAngleY;
        this.mouth2.rotateAngleX = this.neck.rotateAngleX;
        this.mouth2.rotateAngleY = this.neck.rotateAngleY;
        this.rightleg.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 1.4f * par2;
        this.leftleg.rotateAngleX = MathHelper.cos(par1 * 0.6662f + (float)Math.PI) * 1.4f * par2;
        this.rightwing.rotateAngleZ = par3;
        this.leftwing.rotateAngleZ = -par3;
        this.rightwing1.rotateAngleZ = par3;
        this.leftwing1.rotateAngleZ = -par3;
        this.rightwing2.rotateAngleZ = par3;
        this.leftwing2.rotateAngleZ = -par3;
        this.rightwing3.rotateAngleZ = par3;
        this.leftwing3.rotateAngleZ = -par3;
        this.rightwing4.rotateAngleZ = par3;
        this.leftwing4.rotateAngleZ = -par3;
        this.headhair1.rotateAngleX = this.neck.rotateAngleX;
        this.headhair2.rotateAngleX = this.neck.rotateAngleX;
        this.headhair3.rotateAngleX = this.neck.rotateAngleX;
        this.headhair4.rotateAngleX = this.neck.rotateAngleX;
        this.headhair5.rotateAngleX = this.neck.rotateAngleX;
        this.headhair1.rotateAngleY = this.neck.rotateAngleY;
        this.headhair2.rotateAngleY = this.neck.rotateAngleY;
        this.headhair3.rotateAngleY = this.neck.rotateAngleY;
        this.headhair4.rotateAngleY = this.neck.rotateAngleY;
        this.headhair5.rotateAngleY = this.neck.rotateAngleY;
        this.tooth1.rotateAngleX = this.neck.rotateAngleX;
        this.tooth2.rotateAngleX = this.neck.rotateAngleX;
        this.tooth3.rotateAngleX = this.neck.rotateAngleX;
        this.tooth4.rotateAngleX = this.neck.rotateAngleX;
        this.tooth1.rotateAngleY = this.neck.rotateAngleY;
        this.tooth2.rotateAngleY = this.neck.rotateAngleY;
        this.tooth3.rotateAngleY = this.neck.rotateAngleY;
        this.tooth4.rotateAngleY = this.neck.rotateAngleY;
    }
}


