package com.voidsrift.riftflux.wam.client.model;

import com.voidsrift.riftflux.wam.entity.EntityJaxx;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.util.MathHelper;

@SideOnly(Side.CLIENT)public class ModelJaxx
extends ModelBase {
    ModelRenderer Head;
    ModelRenderer Stem;
    ModelRenderer Body;
    ModelRenderer RightArm;
    ModelRenderer LeftArm;
    ModelRenderer RightLeg;
    ModelRenderer LeftLeg;
    ModelRenderer Shoulderr;
    ModelRenderer Neck;
    ModelRenderer Fingerl1;
    ModelRenderer Fingerl2;
    ModelRenderer Shoulderl;
    ModelRenderer Toer2;
    ModelRenderer Toer3;
    ModelRenderer Toel1;
    ModelRenderer Toel2;
    ModelRenderer Toer1;
    ModelRenderer Toel3;
    ModelRenderer Fingerr3;
    ModelRenderer Fingerr1;
    ModelRenderer Fingerr2;
    ModelRenderer Fingerl3;
    ModelRenderer TopFace;
    ModelRenderer BottomFace;
    ModelRenderer MidTopFace;
    ModelRenderer MidBottomFace;
    ModelRenderer LowerFaceRight1;
    ModelRenderer LowerFaceLeft1;
    ModelRenderer LowerFaceRight2;
    ModelRenderer LowerFaceLeft2;
    ModelRenderer UpperJaw;
    ModelRenderer UpperBrow;
    ModelRenderer LowerBrow;
    ModelRenderer NoseBridge;
    ModelRenderer RightEye;
    ModelRenderer LeftEye;
    ModelRenderer FaceRight;
    ModelRenderer FaceLeft;
    ModelRenderer UpperTooth1;
    ModelRenderer UpperTooth2;
    ModelRenderer UpperTooth3;
    ModelRenderer LowerTooth1;
    ModelRenderer LowerTooth2;

    public ModelJaxx() {
        this.textureWidth = 128;
        this.textureHeight = 128;
        this.Head = new ModelRenderer(this, 1, 30);
        this.Head.addBox(-6.0f, -13.0f, -5.0f, 13, 13, 12);
        this.Head.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.Head.setTextureSize(128, 128);
        this.Head.mirror = true;
        this.setRotation(this.Head, 0.0f, 0.0f, 0.0f);
        this.Stem = new ModelRenderer(this, 22, 16);
        this.Stem.addBox(-0.5f, -0.5f, -0.5f, 2, 4, 2);
        this.Stem.setRotationPoint(0.0f, -15.0f, 0.0f);
        this.Stem.setTextureSize(128, 128);
        this.Stem.mirror = true;
        this.setRotation(this.Stem, 0.1745329f, 0.0f, 0.0f);
        this.Body = new ModelRenderer(this, 5, 61);
        this.Body.addBox(-4.0f, 0.0f, -3.0f, 8, 25, 6);
        this.Body.setRotationPoint(0.0f, -29.0f, 0.0f);
        this.Body.setTextureSize(128, 128);
        this.Body.mirror = true;
        this.setRotation(this.Body, 0.0f, 0.0f, 0.0f);
        this.RightArm = new ModelRenderer(this, 56, 40);
        this.RightArm.addBox(-8.0f, -3.0f, -2.0f, 4, 28, 4);
        this.RightArm.setRotationPoint(-3.0f, -24.0f, 0.0f);
        this.RightArm.setTextureSize(128, 128);
        this.RightArm.mirror = true;
        this.setRotation(this.RightArm, 0.0f, 0.0f, 0.0f);
        this.LeftArm = new ModelRenderer(this, 56, 40);
        this.LeftArm.addBox(4.0f, -3.0f, -2.0f, 4, 28, 4);
        this.LeftArm.setRotationPoint(3.0f, -24.0f, 0.0f);
        this.LeftArm.setTextureSize(128, 128);
        this.LeftArm.mirror = true;
        this.setRotation(this.LeftArm, 0.0f, 0.0f, 0.0f);
        this.RightLeg = new ModelRenderer(this, 56, 0);
        this.RightLeg.addBox(-1.5f, 0.0f, -1.5f, 3, 14, 3);
        this.RightLeg.setRotationPoint(-2.5f, -4.0f, 0.0f);
        this.RightLeg.setTextureSize(128, 128);
        this.RightLeg.mirror = true;
        this.setRotation(this.RightLeg, 0.0f, 0.0f, 0.0f);
        this.LeftLeg = new ModelRenderer(this, 56, 0);
        this.LeftLeg.addBox(-1.5f, 0.0f, -1.5f, 3, 14, 3);
        this.LeftLeg.setRotationPoint(2.5f, -4.0f, 0.0f);
        this.LeftLeg.setTextureSize(128, 128);
        this.LeftLeg.mirror = true;
        this.setRotation(this.LeftLeg, 0.0f, 0.0f, 0.0f);
        this.Shoulderr = new ModelRenderer(this, 14, 0);
        this.Shoulderr.addBox(0.0f, -2.0f, -2.0f, 4, 4, 4);
        this.Shoulderr.setRotationPoint(3.0f, -24.0f, 0.0f);
        this.Shoulderr.setTextureSize(128, 128);
        this.Shoulderr.mirror = true;
        this.setRotation(this.Shoulderr, 0.0f, 0.0f, 0.0f);
        this.Neck = new ModelRenderer(this, 34, 15);
        this.Neck.addBox(-1.5f, -3.0f, -1.5f, 3, 4, 3);
        this.Neck.setRotationPoint(0.0f, -29.0f, 0.0f);
        this.Neck.setTextureSize(128, 128);
        this.Neck.mirror = true;
        this.setRotation(this.Neck, 0.0f, 0.0f, 0.0f);
        this.Fingerl1 = new ModelRenderer(this, 44, 61);
        this.Fingerl1.addBox(7.0f, 25.0f, 0.0f, 1, 9, 1);
        this.Fingerl1.setRotationPoint(3.0f, -24.0f, 0.0f);
        this.Fingerl1.setTextureSize(128, 128);
        this.Fingerl1.mirror = true;
        this.setRotation(this.Fingerl1, 0.0f, 0.0f, 0.0f);
        this.Fingerl2 = new ModelRenderer(this, 44, 61);
        this.Fingerl2.addBox(4.0f, 25.0f, 1.0f, 1, 9, 1);
        this.Fingerl2.setRotationPoint(3.0f, -24.0f, 0.0f);
        this.Fingerl2.setTextureSize(128, 128);
        this.Fingerl2.mirror = true;
        this.setRotation(this.Fingerl2, 0.0f, 0.0f, 0.0f);
        this.Shoulderl = new ModelRenderer(this, 36, 0);
        this.Shoulderl.addBox(-4.0f, -2.0f, -2.0f, 4, 4, 4);
        this.Shoulderl.setRotationPoint(-3.0f, -24.0f, 0.0f);
        this.Shoulderl.setTextureSize(128, 128);
        this.Shoulderl.mirror = true;
        this.setRotation(this.Shoulderl, 0.0f, 0.0f, 0.0f);
        this.Toer2 = new ModelRenderer(this, 0, 0);
        this.Toer2.addBox(-0.5f, 9.0f, -1.0f, 2, 19, 2);
        this.Toer2.setRotationPoint(-2.5f, -4.0f, 0.0f);
        this.Toer2.setTextureSize(128, 128);
        this.Toer2.mirror = true;
        this.setRotation(this.Toer2, 0.0f, 0.0f, 0.1047198f);
        this.Toer3 = new ModelRenderer(this, 0, 0);
        this.Toer3.addBox(-0.5f, 9.0f, -1.5f, 2, 19, 2);
        this.Toer3.setRotationPoint(-2.5f, -4.0f, 0.0f);
        this.Toer3.setTextureSize(128, 128);
        this.Toer3.mirror = true;
        this.setRotation(this.Toer3, 0.1047198f, 0.0f, 0.0f);
        this.Toer1 = new ModelRenderer(this, 0, 0);
        this.Toer1.addBox(-0.5f, 9.0f, 0.0f, 2, 19, 2);
        this.Toer1.setRotationPoint(-2.5f, -4.0f, 0.0f);
        this.Toer1.setTextureSize(128, 128);
        this.Toer1.mirror = true;
        this.setRotation(this.Toer1, -0.122173f, 0.0f, 0.0f);
        this.Toel2 = new ModelRenderer(this, 0, 0);
        this.Toel2.addBox(-1.5f, 9.0f, -1.0f, 2, 19, 2);
        this.Toel2.setRotationPoint(2.5f, -4.0f, 0.0f);
        this.Toel2.setTextureSize(128, 128);
        this.Toel2.mirror = true;
        this.setRotation(this.Toel2, 0.0f, 0.0f, -0.1047198f);
        this.Toel1 = new ModelRenderer(this, 0, 0);
        this.Toel1.addBox(-1.0f, 9.0f, 0.0f, 2, 19, 2);
        this.Toel1.setRotationPoint(2.5f, -4.0f, 0.0f);
        this.Toel1.setTextureSize(128, 128);
        this.Toel1.mirror = true;
        this.setRotation(this.Toel1, -0.122173f, 0.0f, 0.0f);
        this.Toel3 = new ModelRenderer(this, 0, 0);
        this.Toel3.addBox(-1.5f, 9.0f, -1.5f, 2, 19, 2);
        this.Toel3.setRotationPoint(2.5f, -4.0f, 0.0f);
        this.Toel3.setTextureSize(128, 128);
        this.Toel3.mirror = true;
        this.setRotation(this.Toel3, 0.1047198f, 0.0f, 0.0f);
        this.Fingerr3 = new ModelRenderer(this, 44, 61);
        this.Fingerr3.addBox(-6.0f, 25.0f, -2.0f, 1, 9, 1);
        this.Fingerr3.setRotationPoint(-3.0f, -24.0f, 0.0f);
        this.Fingerr3.setTextureSize(128, 128);
        this.Fingerr3.mirror = true;
        this.setRotation(this.Fingerr3, 0.0f, 0.0f, 0.0f);
        this.Fingerr1 = new ModelRenderer(this, 44, 61);
        this.Fingerr1.addBox(-8.0f, 25.0f, 0.0f, 1, 9, 1);
        this.Fingerr1.setRotationPoint(-3.0f, -24.0f, 0.0f);
        this.Fingerr1.setTextureSize(128, 128);
        this.Fingerr1.mirror = true;
        this.setRotation(this.Fingerr1, 0.0f, 0.0f, 0.0f);
        this.Fingerr2 = new ModelRenderer(this, 44, 61);
        this.Fingerr2.addBox(-5.0f, 25.0f, 1.0f, 1, 9, 1);
        this.Fingerr2.setRotationPoint(-3.0f, -24.0f, 0.0f);
        this.Fingerr2.setTextureSize(128, 128);
        this.Fingerr2.mirror = true;
        this.setRotation(this.Fingerr2, 0.0f, 0.0f, 0.0f);
        this.Fingerl3 = new ModelRenderer(this, 44, 61);
        this.Fingerl3.addBox(5.0f, 25.0f, -2.0f, 1, 9, 1);
        this.Fingerl3.setRotationPoint(3.0f, -24.0f, 0.0f);
        this.Fingerl3.setTextureSize(128, 128);
        this.Fingerl3.mirror = true;
        this.setRotation(this.Fingerl3, 0.0f, 0.0f, 0.0f);
        this.TopFace = new ModelRenderer(this, 0, 122);
        this.TopFace.addBox(-6.0f, -13.0f, -6.0f, 13, 2, 1);
        this.TopFace.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.TopFace.setTextureSize(128, 128);
        this.TopFace.mirror = true;
        this.setRotation(this.TopFace, 0.0f, 0.0f, 0.0f);
        this.BottomFace = new ModelRenderer(this, 0, 118);
        this.BottomFace.addBox(-6.0f, -2.0f, -6.0f, 13, 2, 1);
        this.BottomFace.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.BottomFace.setTextureSize(128, 128);
        this.BottomFace.mirror = true;
        this.setRotation(this.BottomFace, 0.0f, 0.0f, 0.0f);
        this.MidTopFace = new ModelRenderer(this, 0, 114);
        this.MidTopFace.addBox(-5.0f, -8.0f, -6.0f, 11, 1, 1);
        this.MidTopFace.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.MidTopFace.setTextureSize(128, 128);
        this.MidTopFace.mirror = true;
        this.setRotation(this.MidTopFace, 0.0f, 0.0f, 0.0f);
        this.MidBottomFace = new ModelRenderer(this, 0, 110);
        this.MidBottomFace.addBox(-5.0f, -7.0f, -6.0f, 11, 2, 1);
        this.MidBottomFace.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.MidBottomFace.setTextureSize(128, 128);
        this.MidBottomFace.mirror = true;
        this.setRotation(this.MidBottomFace, 0.0f, 0.0f, 0.0f);
        this.LowerFaceRight1 = new ModelRenderer(this, 30, 110);
        this.LowerFaceRight1.addBox(-5.0f, -4.0f, -6.0f, 1, 2, 1);
        this.LowerFaceRight1.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.LowerFaceRight1.setTextureSize(128, 128);
        this.LowerFaceRight1.mirror = true;
        this.setRotation(this.LowerFaceRight1, 0.0f, 0.0f, 0.0f);
        this.LowerFaceLeft1 = new ModelRenderer(this, 36, 110);
        this.LowerFaceLeft1.addBox(5.0f, -4.0f, -6.0f, 1, 2, 1);
        this.LowerFaceLeft1.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.LowerFaceLeft1.setTextureSize(128, 128);
        this.LowerFaceLeft1.mirror = true;
        this.setRotation(this.LowerFaceLeft1, 0.0f, 0.0f, 0.0f);
        this.LowerFaceRight2 = new ModelRenderer(this, 24, 98);
        this.LowerFaceRight2.addBox(-4.0f, -3.0f, -6.0f, 1, 1, 1);
        this.LowerFaceRight2.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.LowerFaceRight2.setTextureSize(128, 128);
        this.LowerFaceRight2.mirror = true;
        this.setRotation(this.LowerFaceRight2, 0.0f, 0.0f, 0.0f);
        this.LowerFaceLeft2 = new ModelRenderer(this, 42, 98);
        this.LowerFaceLeft2.addBox(4.0f, -3.0f, -6.0f, 1, 1, 1);
        this.LowerFaceLeft2.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.LowerFaceLeft2.setTextureSize(128, 128);
        this.LowerFaceLeft2.mirror = true;
        this.setRotation(this.LowerFaceLeft2, 0.0f, 0.0f, 0.0f);
        this.UpperJaw = new ModelRenderer(this, 0, 94);
        this.UpperJaw.addBox(-3.0f, -5.0f, -6.0f, 7, 1, 1);
        this.UpperJaw.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.UpperJaw.setTextureSize(128, 128);
        this.UpperJaw.mirror = true;
        this.setRotation(this.UpperJaw, 0.0f, 0.0f, 0.0f);
        this.UpperBrow = new ModelRenderer(this, 0, 106);
        this.UpperBrow.addBox(-4.0f, -11.0f, -6.0f, 9, 1, 1);
        this.UpperBrow.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.UpperBrow.setTextureSize(128, 128);
        this.UpperBrow.mirror = true;
        this.setRotation(this.UpperBrow, 0.0f, 0.0f, 0.0f);
        this.LowerBrow = new ModelRenderer(this, 0, 102);
        this.LowerBrow.addBox(-2.0f, -10.0f, -6.0f, 5, 1, 1);
        this.LowerBrow.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.LowerBrow.setTextureSize(128, 128);
        this.LowerBrow.mirror = true;
        this.setRotation(this.LowerBrow, 0.0f, 0.0f, 0.0f);
        this.NoseBridge = new ModelRenderer(this, 0, 98);
        this.NoseBridge.addBox(-1.0f, -9.0f, -6.0f, 3, 1, 1);
        this.NoseBridge.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.NoseBridge.setTextureSize(128, 128);
        this.NoseBridge.mirror = true;
        this.setRotation(this.NoseBridge, 0.0f, 0.0f, 0.0f);
        this.RightEye = new ModelRenderer(this, 42, 122);
        this.RightEye.addBox(-5.0f, -10.0f, -6.0f, 1, 2, 1);
        this.RightEye.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.RightEye.setTextureSize(128, 128);
        this.RightEye.mirror = true;
        this.setRotation(this.RightEye, 0.0f, 0.0f, 0.0f);
        this.LeftEye = new ModelRenderer(this, 42, 117);
        this.LeftEye.addBox(5.0f, -10.0f, -6.0f, 1, 2, 1);
        this.LeftEye.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.LeftEye.setTextureSize(128, 128);
        this.LeftEye.mirror = true;
        this.setRotation(this.LeftEye, 0.0f, 0.0f, 0.0f);
        this.FaceRight = new ModelRenderer(this, 30, 116);
        this.FaceRight.addBox(-6.0f, -11.0f, -6.0f, 1, 9, 1);
        this.FaceRight.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.FaceRight.setTextureSize(128, 128);
        this.FaceRight.mirror = true;
        this.setRotation(this.FaceRight, 0.0f, 0.0f, 0.0f);
        this.FaceLeft = new ModelRenderer(this, 36, 116);
        this.FaceLeft.addBox(6.0f, -11.0f, -6.0f, 1, 9, 1);
        this.FaceLeft.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.FaceLeft.setTextureSize(128, 128);
        this.FaceLeft.mirror = true;
        this.setRotation(this.FaceLeft, 0.0f, 0.0f, 0.0f);
        this.UpperTooth1 = new ModelRenderer(this, 30, 104);
        this.UpperTooth1.addBox(-3.0f, -4.0f, -6.0f, 1, 1, 1);
        this.UpperTooth1.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.UpperTooth1.setTextureSize(128, 128);
        this.UpperTooth1.mirror = true;
        this.setRotation(this.UpperTooth1, 0.0f, 0.0f, 0.0f);
        this.UpperTooth2 = new ModelRenderer(this, 36, 104);
        this.UpperTooth2.addBox(0.0f, -4.0f, -6.0f, 1, 1, 1);
        this.UpperTooth2.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.UpperTooth2.setTextureSize(128, 128);
        this.UpperTooth2.mirror = true;
        this.setRotation(this.UpperTooth2, 0.0f, 0.0f, 0.0f);
        this.UpperTooth3 = new ModelRenderer(this, 42, 104);
        this.UpperTooth3.addBox(2.0f, -4.0f, -6.0f, 1, 1, 1);
        this.UpperTooth3.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.UpperTooth3.setTextureSize(128, 128);
        this.UpperTooth3.mirror = true;
        this.setRotation(this.UpperTooth3, 0.0f, 0.0f, 0.0f);
        this.LowerTooth1 = new ModelRenderer(this, 30, 98);
        this.LowerTooth1.addBox(-1.0f, -3.0f, -6.0f, 1, 1, 1);
        this.LowerTooth1.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.LowerTooth1.setTextureSize(128, 128);
        this.LowerTooth1.mirror = true;
        this.setRotation(this.LowerTooth1, 0.0f, 0.0f, 0.0f);
        this.LowerTooth2 = new ModelRenderer(this, 36, 98);
        this.LowerTooth2.addBox(1.0f, -3.0f, -6.0f, 1, 1, 1);
        this.LowerTooth2.setRotationPoint(0.0f, -31.0f, 0.0f);
        this.LowerTooth2.setTextureSize(128, 128);
        this.LowerTooth2.mirror = true;
        this.setRotation(this.LowerTooth2, 0.0f, 0.0f, 0.0f);
        this.Head.addChild(this.Stem);
    }

    public void render(Entity var1, float var2, float var3, float var4, float var5, float var6, float var7) {
        this.setRotationAngles(var2, var3, var4, var5, var6, var7, var1);
        this.Head.render(var7);
        this.Body.render(var7);
        this.RightArm.render(var7);
        this.LeftArm.render(var7);
        this.RightLeg.render(var7);
        this.LeftLeg.render(var7);
        this.Shoulderr.render(var7);
        this.Neck.render(var7);
        this.Fingerl1.render(var7);
        this.Fingerl2.render(var7);
        this.Shoulderl.render(var7);
        this.Toer1.render(var7);
        this.Toer2.render(var7);
        this.Toer3.render(var7);
        this.Toel1.render(var7);
        this.Toel2.render(var7);
        this.Toel3.render(var7);
        this.Fingerr3.render(var7);
        this.Fingerr1.render(var7);
        this.Fingerr2.render(var7);
        this.Fingerl3.render(var7);
        this.TopFace.render(var7);
        this.BottomFace.render(var7);
        this.MidTopFace.render(var7);
        this.MidBottomFace.render(var7);
        this.LowerFaceRight1.render(var7);
        this.LowerFaceLeft1.render(var7);
        this.LowerFaceRight2.render(var7);
        this.LowerFaceLeft2.render(var7);
        this.UpperJaw.render(var7);
        this.UpperBrow.render(var7);
        this.LowerBrow.render(var7);
        this.NoseBridge.render(var7);
        this.RightEye.render(var7);
        this.LeftEye.render(var7);
        this.FaceRight.render(var7);
        this.FaceLeft.render(var7);
        this.UpperTooth1.render(var7);
        this.UpperTooth2.render(var7);
        this.UpperTooth3.render(var7);
        this.LowerTooth1.render(var7);
        this.LowerTooth2.render(var7);
    }

    public void setRotationAngles(float var1, float var2, float var3, float var4, float var5, float var6, Entity entity) {
        this.Head.rotateAngleY = var4 / 57.295776f;
        this.Head.rotateAngleX = var5 / 57.295776f;
        this.TopFace.rotateAngleY = this.Head.rotateAngleY;
        this.BottomFace.rotateAngleY = this.Head.rotateAngleY;
        this.MidTopFace.rotateAngleY = this.Head.rotateAngleY;
        this.MidBottomFace.rotateAngleY = this.Head.rotateAngleY;
        this.LowerFaceRight1.rotateAngleY = this.Head.rotateAngleY;
        this.LowerFaceLeft1.rotateAngleY = this.Head.rotateAngleY;
        this.LowerFaceRight2.rotateAngleY = this.Head.rotateAngleY;
        this.LowerFaceLeft2.rotateAngleY = this.Head.rotateAngleY;
        this.UpperJaw.rotateAngleY = this.Head.rotateAngleY;
        this.UpperBrow.rotateAngleY = this.Head.rotateAngleY;
        this.LowerBrow.rotateAngleY = this.Head.rotateAngleY;
        this.NoseBridge.rotateAngleY = this.Head.rotateAngleY;
        this.RightEye.rotateAngleY = this.Head.rotateAngleY;
        this.LeftEye.rotateAngleY = this.Head.rotateAngleY;
        this.FaceRight.rotateAngleY = this.Head.rotateAngleY;
        this.FaceLeft.rotateAngleY = this.Head.rotateAngleY;
        this.UpperTooth1.rotateAngleY = this.Head.rotateAngleY;
        this.UpperTooth2.rotateAngleY = this.Head.rotateAngleY;
        this.UpperTooth3.rotateAngleY = this.Head.rotateAngleY;
        this.LowerTooth1.rotateAngleY = this.Head.rotateAngleY;
        this.LowerTooth2.rotateAngleY = this.Head.rotateAngleY;
        this.TopFace.rotateAngleX = this.Head.rotateAngleX;
        this.BottomFace.rotateAngleX = this.Head.rotateAngleX;
        this.MidTopFace.rotateAngleX = this.Head.rotateAngleX;
        this.MidBottomFace.rotateAngleX = this.Head.rotateAngleX;
        this.LowerFaceRight1.rotateAngleX = this.Head.rotateAngleX;
        this.LowerFaceLeft1.rotateAngleX = this.Head.rotateAngleX;
        this.LowerFaceRight2.rotateAngleX = this.Head.rotateAngleX;
        this.LowerFaceLeft2.rotateAngleX = this.Head.rotateAngleX;
        this.UpperJaw.rotateAngleX = this.Head.rotateAngleX;
        this.UpperBrow.rotateAngleX = this.Head.rotateAngleX;
        this.LowerBrow.rotateAngleX = this.Head.rotateAngleX;
        this.NoseBridge.rotateAngleX = this.Head.rotateAngleX;
        this.RightEye.rotateAngleX = this.Head.rotateAngleX;
        this.LeftEye.rotateAngleX = this.Head.rotateAngleX;
        this.FaceRight.rotateAngleX = this.Head.rotateAngleX;
        this.FaceLeft.rotateAngleX = this.Head.rotateAngleX;
        this.UpperTooth1.rotateAngleX = this.Head.rotateAngleX;
        this.UpperTooth2.rotateAngleX = this.Head.rotateAngleX;
        this.UpperTooth3.rotateAngleX = this.Head.rotateAngleX;
        this.LowerTooth1.rotateAngleX = this.Head.rotateAngleX;
        this.LowerTooth2.rotateAngleX = this.Head.rotateAngleX;
        this.Stem.rotateAngleY = this.Head.rotateAngleY;
        this.Stem.rotateAngleX = this.Head.rotateAngleX + 0.1745329f;
        this.RightLeg.rotateAngleX = -1.5f * this.func_48228_a(var1, 13.0f) * var2;
        this.LeftLeg.rotateAngleX = 1.5f * this.func_48228_a(var1, 13.0f) * var2;
        this.RightLeg.rotateAngleY = 0.0f;
        this.LeftLeg.rotateAngleY = 0.0f;
        this.Toer2.rotateAngleX = this.RightLeg.rotateAngleX;
        this.Toer3.rotateAngleX = this.RightLeg.rotateAngleX + 0.1047198f;
        this.Toel1.rotateAngleX = this.LeftLeg.rotateAngleX - 0.122173f;
        this.Toel2.rotateAngleX = this.LeftLeg.rotateAngleX;
        this.Toer1.rotateAngleX = this.RightLeg.rotateAngleX - 0.122173f;
        this.Toel3.rotateAngleX = this.LeftLeg.rotateAngleX + 0.1047198f;
        this.Toer2.rotateAngleZ = this.RightLeg.rotateAngleZ + 0.1047198f;
        this.Toel2.rotateAngleZ = this.LeftLeg.rotateAngleZ - 0.1047198f;
    }

    public void setLivingAnimations(EntityLivingBase var1, float var2, float var3, float var4) {
        int var6 = var1 instanceof EntityJaxx ? ((EntityJaxx)var1).getAttackTimer() : 0;
        if (var6 > 0) {
            this.RightArm.rotateAngleX = -2.0f + 1.5f * this.func_48228_a((float)var6 - var4, 10.0f);
            this.LeftArm.rotateAngleX = -2.0f + 1.5f * this.func_48228_a((float)var6 - var4, 10.0f);
            this.Shoulderr.rotateAngleX = this.RightArm.rotateAngleX;
            this.Shoulderl.rotateAngleX = this.LeftArm.rotateAngleX;
            this.Fingerr3.rotateAngleX = this.RightArm.rotateAngleX;
            this.Fingerr2.rotateAngleX = this.RightArm.rotateAngleX;
            this.Fingerr1.rotateAngleX = this.RightArm.rotateAngleX;
            this.Fingerl3.rotateAngleX = this.LeftArm.rotateAngleX;
            this.Fingerl2.rotateAngleX = this.LeftArm.rotateAngleX;
            this.Fingerl1.rotateAngleX = this.LeftArm.rotateAngleX;
        } else {
            this.RightArm.rotateAngleX = (-0.2f + 1.5f * this.func_48228_a(var2, 13.0f)) * var3;
            this.LeftArm.rotateAngleX = (-0.2f - 1.5f * this.func_48228_a(var2, 13.0f)) * var3;
            this.Shoulderr.rotateAngleX = this.RightArm.rotateAngleX;
            this.Shoulderl.rotateAngleX = this.LeftArm.rotateAngleX;
            this.Fingerr3.rotateAngleX = this.RightArm.rotateAngleX;
            this.Fingerr2.rotateAngleX = this.RightArm.rotateAngleX;
            this.Fingerr1.rotateAngleX = this.RightArm.rotateAngleX;
            this.Fingerl3.rotateAngleX = this.LeftArm.rotateAngleX;
            this.Fingerl2.rotateAngleX = this.LeftArm.rotateAngleX;
            this.Fingerl1.rotateAngleX = this.LeftArm.rotateAngleX;
        }
    }

    private float func_48228_a(float var1, float var2) {
        return (Math.abs(var1 % var2 - var2 * 0.5f) - var2 * 0.25f) / (var2 * 0.25f);
    }

    private void setRotation(ModelRenderer var1, float var2, float var3, float var4) {
        var1.rotateAngleX = var2;
        var1.rotateAngleY = var3;
        var1.rotateAngleZ = var4;
    }
}

