package com.voidsrift.riftflux.mixin.early;

import com.voidsrift.riftflux.ModConfig;
import com.voidsrift.riftflux.util.RFPlantContext;
import net.minecraft.block.Block;
import net.minecraft.block.BlockBush;
import net.minecraft.init.Blocks;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

/**
 * Allows all BlockBush-based plants (tall grass, flowers, double plants, etc.)
 * to be placed on ANY non-air block when enabled in the config,
 * but never on air.
 *
 * During bonemeal-driven growth, we DO NOT override vanilla logic, so plants
 * generated by bonemeal still obey the usual "must be on grass/dirt/etc."
 * rules and won't appear on stone, glass, or floating.
 */
@Mixin(BlockBush.class)
public abstract class MixinBlockBush_AnySupport {

    @Inject(method = "canPlaceBlockOn", at = @At("HEAD"), cancellable = true)
    private void riftflux$allowPlantsOnAnyNonAirBlock(Block ground, CallbackInfoReturnable<Boolean> cir) {
        // If the feature is disabled, use vanilla rules.
        if (!ModConfig.allowPlantsOnAnyBlock) {
            return;
        }

        // When bonemeal is actively growing foliage, DO NOT override vanilla.
        // This keeps bonemeal growth restricted to valid vanilla blocks (e.g. grass).
        if (RFPlantContext.bonemealPlacementActive) {
            return;
        }

        // Normal placement / survival: allow BlockBush on any non-air block.
        if (ground != null && ground != Blocks.air) {
            cir.setReturnValue(true);
        } else {
            // Explicitly disallow "standing on air".
            cir.setReturnValue(false);
        }
    }
}
